{
  "hash": "1de4995af964292bba7994ab01aaf17e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Detecting item misfit in Rasch models\"\nauthor:\n  - name: Magnus Johansson, PhD\n    affiliations:\n      - name: RISE Research Institutes of Sweden, Division Built Environment, System Transition\n      - name: Centre for Psychiatry Research, Department of Clinical Neuroscience, Karolinska Institutet, & Stockholm Health Care Services, Region Stockholm\n    orcid: 0000-0003-1669-592X\n    email: pgmj@pm.me\n    corresponding: true\nkeywords:\n  - Rasch\n  - Psychometrics\n  - Item fit\n  - Cutoffs\n  - Critical values\n  - Model fit\nabstract: |\n  Psychometrics have long relied on rule-of-thumb critical values for goodness of fit metrics. With  powerful personal computers it is both feasible and desirable to use simulation methods to determine appropriate cutoff values. This paper evaluates the use of an R package for Rasch psychometrics that has implemented functions to simplify the process of determining simulation-based cutoff values. Through six simulation studies, comparisons are made between information-weighted conditional item fit (\"infit\") and item-restscore correlations using Goodman and Kruskal’s $\\gamma$. Results indicate the limitations of small samples (n < 500) in correctly detecting item misfit, especially when a larger proportion of items are misfit and/or when misfit items are off-target. Infit with simulation-based cutoffs outperforms item-restscore with sample sizes below 500. Both methods result in problematic rates of false positives with large samples (n >= 1000). Large datasets should be analyzed using nonparametric bootstrap of subsamples with item-restscore to reduce the risk of type-1 errors. Finally, the importance of an iterative analysis process is emphasized, since a situation where several items show underfit will cause other items to show overfit. Underfit items should be removed one at a time, and a re-analysis conducted for each step to avoid erroneously eliminating items.\nkey-points:\n  - Rule-of-thumb critical values for item fit metrics should be replaced with simulation-based values\n  - Sample size affects the detection rate and false positive rate\n  - More misfitting items increase the false positive rate\n  - Mean squared unweighted \"outfit\" is not useful\ndate: last-modified\nbibliography: references.bib\nshorttitle: Detecting item misfit in Rasch models\nnotebook-links: global\nlicense: \"CC BY\"\nfunding: \"The author received no specific funding for this work.\"\ncitation:\n  doi: 10.31219/osf.io/j8fg2\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n# Introduction\n\nThis paper presents a series of simulations conducted to evaluate methods to detect item misfit due to multidimensionality in Rasch models. First, conditional item infit and outfit [@muller_item_2020] will be under scrutiny. Second, item infit will be compared to the item-restscore method [@kreiner_note_2011;@christensen_item_2013]. Third, a bootstrap method for item-restscore will be presented and tested. This paper is intended for a target group of those who make practical use of Rasch analysis and wish to better understand the expected performance of methods available. As such, we refer readers interested in mathematical and statistical descriptions of the methods to referenced papers detailing this aspect. Only two simple performance metrics will be presented in the results: correct detection rate and false positive rate, both in percentages.\n\nThe evaluation of item fit under the Rasch model has, in the majority of published psychometric papers, been conducted using various more or less arbitrary rule-of-thumb critical values. Regarding mean squared (MSQ) item residuals, which should ideally be centered around 1.0, there are two sources often cited. One is the book by Bond and Fox [-@bond_applying_2015], which has garnered around 12 000 citations according to Google Scholar. It contains a table with rule-of-thumb recommendations for various settings, ranging from 0.8–1.2 to 0.5–1.7. Another frequently seen source, which is not an actual peer-reviewed publication and thus lacks citation counts, is the webpage at <https://rasch.org/rmt/rmt162f.htm>, where Mike Linacre states 0.5-1.5 to be \"productive for measurement\". Neither of these sources seem to rely on simulation studies to support their recommendations. While it is reasonable to accept a non-perfect fit to the Rasch model and also describe what one defines as acceptable levels of misfit, such recommendations would seem less arbitrary if related to simulations showing the range of item fit values found when simulating data that fit the Rasch model.\n\nMüller [-@muller_item_2020] used simulation to show how the range of critical values for conditional item infit varies with sample size. The expected average conditional item infit range was described by Müller as fairly well captured by Smith's rule-of-thumb formula 1±2/$\\sqrt{n}$ [@smith_using_1998], where n denotes the sample size. However, the average range does not apply for all items within a dataset, since item location relative to sample mean location also affects the expected model fit for individual items. This means that some items within a set of items varying in location are likely to have item fit values outside Smith's average value range while still fitting the Rasch model. Although primarily affecte by sample size, each item has its variations in the range of expected item fit.\n\nWhile evaluation of item fit is an essential part of evaluating unidimensionality, it is recommended to use multiple methods. Standardized residuals are frequently analyzed, commonly with principal component analysis (PCA) and an analysis of residual correlations amongst item pairs, often referred to as Yen's Q3. Chou and Wang [-@chou_checking_2010] showed that the critical value for PCA of residuals to support unidimensionality suggested by Smith [-@smith_detecting_2002], using the largest eigenvalue < 1.5, is not generally applicable since it is affected by both test length and sample size. Christensen and colleagues [-@christensen_critical_2017] used simulation methods to illustrate the expected range of residual correlations under different conditions. Both of these papers provide important information about the dubiousness of using rule-of-thumb critical values when the empirical distribution of a statistic is not known, but they leave practitioners without tools to determine appropriate cutoffs to apply in practical analysis work.\n\nIt is here proposed that by using parametric bootstrapping one can establish item fit critical cutoff values that are relevant for a specific sample and item set. The procedure uses the estimated properties of the available data and simulates multiple new response datasets that fit the Rasch model to determine the range of plausible item fit values for each item. The R package `easyRasch` [@easyrasch] includes a function to determine item infit and outfit cutoff values using this method and will be tested in the simulation studies in this paper.\n\nSimilar developments, moving from rule-of-thumb towards adaptive critical values, have recently taken place in the related field of confirmatory factor analysis. McNeish and Wolf [-@mcneish_direct_2024] have created an R package called `dynamic` that uses simulation to determine appropriate critical values for commonly used model fit metrics for models using ordinal or interval data. \n\nIt is important to note that the conditional item fit described by Müller [-@muller_item_2020] and implemented in the `iarm` R package [@mueller_iarm_2022] should not be confused with the unconditional item fit implemented in software such as Winsteps and RUMM2030, as well as all R packages except `iarm`. Unconditional item fit can result in unreliable item fit in sample sizes as small as 200 with an increasing probability of problems as sample size increases. Readers are strongly recommended to read Müller's paper to fully understand the issues with unconditional item fit. Additionally, the experienced Rasch analyst will perhaps wonder why the Wilson-Hilferty transformed Z statistic (often abbreviated ZSTD), which is based on unconditional MSQ is not included in this analysis. This is also explained in Müller's paper, where she describes both the notorious problems with sample size and shows that conditional item fit makes ZSTD superfluous. The `easyRasch` package, which is used in this paper, uses the `iarm` implementation of conditional item fit.\n\nCurrently, there are no published studies on the performance the item-restscore method, as described by Kreiner and Christensen [@kreiner_note_2011;@christensen_item_2013], in detecting misfitting items. Comparing it with an improved version of the long used item infit/outfit methods seemed like a good setting to evaluate item-restscore. The conditional likelihood ratio test [@andersen_goodness_1973] is included in Study 6, since it is a global test of fit that many are likely to be familiar with. As such, it also serves as a point of reference.\n\nThere are six simulation studies included in this paper:\n\n1. Conditional item infit and outfit\n2. Item-restscore\n3. Comparing infit and item-restscore\n4. Bootstrapped item-restscore\n5. Varying the number of items\n6. Conditional likelihood ratio test\n\n# Methods \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(iarm)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: eRm\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: ggplot2\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(eRm)\nlibrary(ggdist)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n-- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --\nv dplyr     1.1.4     v readr     2.1.5\nv forcats   1.0.0     v stringr   1.5.1\nv lubridate 1.9.3     v tibble    3.2.1\nv purrr     1.0.2     v tidyr     1.3.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n-- Conflicts ------------------------------------------ tidyverse_conflicts() --\nx dplyr::filter() masks stats::filter()\nx dplyr::lag()    masks stats::lag()\ni Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(easyRasch)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: formattable\nLoading required package: kableExtra\n\nAttaching package: 'kableExtra'\n\nThe following object is masked from 'package:dplyr':\n\n    group_rows\n\nLoading required package: mirt\nLoading required package: stats4\nLoading required package: lattice\n\nAttaching package: 'mirt'\n\nThe following objects are masked from 'package:eRm':\n\n    itemfit, personfit\n\nLoading required package: psych\n\nAttaching package: 'psych'\n\nThe following objects are masked from 'package:ggplot2':\n\n    %+%, alpha\n\nThe following object is masked from 'package:eRm':\n\n    sim.rasch\n\nLoading required package: psychotree\nLoading required package: partykit\nLoading required package: grid\nLoading required package: libcoin\nLoading required package: mvtnorm\nLoading required package: psychotools\nLoading required package: matrixStats\n\nAttaching package: 'matrixStats'\n\nThe following object is masked from 'package:dplyr':\n\n    count\n\nLoading required package: reshape\n\nAttaching package: 'reshape'\n\nThe following object is masked from 'package:lubridate':\n\n    stamp\n\nThe following object is masked from 'package:dplyr':\n\n    rename\n\nThe following objects are masked from 'package:tidyr':\n\n    expand, smiths\n\nLoading required package: patchwork\n\nAttaching package: 'patchwork'\n\nThe following object is masked from 'package:formattable':\n\n    area\n\nLoading required package: ggrepel\nLoading required package: glue\nLoading required package: catR\nLoading required package: hexbin\nLoading required package: janitor\n\nAttaching package: 'janitor'\n\nThe following objects are masked from 'package:stats':\n\n    chisq.test, fisher.test\n\nLoading required package: foreach\n\nAttaching package: 'foreach'\n\nThe following objects are masked from 'package:purrr':\n\n    accumulate, when\n\nLoading required package: furrr\nLoading required package: future\nLoading required package: doParallel\nLoading required package: iterators\nLoading required package: parallel\nThis is easyRasch 0.3.5. Check for updates at <https://pgmj.github.io/easyRasch/news/index.html>\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(arrow)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSome features are not enabled in this build of Arrow. Run `arrow_info()` for more information.\nThe repository you retrieved Arrow from did not include all of Arrow's features.\nYou can install a fully-featured version by running:\n`install.packages('arrow', repos = 'https://apache.r-universe.dev')`.\n\nAttaching package: 'arrow'\n\nThe following object is masked from 'package:lubridate':\n\n    duration\n\nThe following object is masked from 'package:utils':\n\n    timestamp\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(showtext)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: sysfonts\nLoading required package: showtextdb\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nshowtext_auto()\n\n### some commands exist in multiple packages, here we define preferred ones that are frequently used\nselect <- dplyr::select\ncount <- dplyr::count\nrename <- dplyr::rename\n\ntheme_rise <- theme_rise(fontfamily = \"sans\")\n```\n:::\n\n\n\n\n\nThis is a general description of the methods used. Each study included in this paper has its own brief introduction and method section. A reproducible manuscript with R code and data is available on GitHub: <https://github.com/pgmj/rasch_itemfit>. First, a note on terminology. Non-parametric bootstrapping is synonymous with sampling with replacement. With this method, the original response data is directly sampled from multiple times. Parametric bootstrapping is synonymous with simulation, since new data is generated based on person and item parameter estimates from the original response data.\n\nThe simulation of response data used three steps: First, a vector of theta values (person scores on the latent variable's logit scale) was generated using `rnorm(mean = 0, sd = 1.5)`. Second, a set of item locations ranging from -2 to 2 logits were generated for dichotomous items, using `runif(n = 20, min = -2, max = 2)`. The same set of item locations were used for all studies except Study 5, which adds 20 more item locations. Third, the theta values were used to simulate item responses for participants, using `sim.xdim()` from the `eRm` package [@mair_extended_2007], which allows the simulation of multidimensional response data. The sigma matrix used by `sim.xdim()` was specified to use 0.15 on the off-diagonal, where values are between 0 and 1 with lower values indicating stronger multidimensionality. Multiple datasets with 10 000 respondents each were generated using the same item and person parameters, varying the targeting of the misfitting item(s) and number of the misfitting item(s). More details are described in the separate studies. The parametric bootstrapping procedure was implemented using random samples from the simulated datasets. Sample size variations tested are also described in each study. \n\nThe general procedure for the parametric bootstrap was as follows:\n\n1. Estimation of item locations based on simulated item response data, using Conditional Maximum Likelihood [CML, @mair_extended_2007].\n2. Estimation of sample theta values using weighted maximum likelihood [@warm_weighted_1989].\n3. Simulation of new response data that fit the Rasch model, using the estimated item locations and theta values.\n4. Estimation of the dichotomous Rasch model for the new response data using CML.\n5. Based on step 4, calculation of conditional item infit and outfit [@muller_item_2020;@mueller_iarm_2022] and/or item-restscore metrics [@kreiner_note_2011;@mueller_iarm_2022].\n\nSteps three and four were iterated over, using sampling with replacement from the estimated theta values as a basis for simulating the response data in step three. Summary statistics were created with a focus on the percentage of correct detection of misfit and false positives. A complete list of software used for the analyses is listed under @sec-addmat.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# read pre-generated item locations for reproducibility\nitems1 <- read_csv(\"data/rm_items40.csv\") %>%\n  slice(1:20) %>% \n  pull(location)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 40 Columns: 2\n-- Column specification --------------------------------------------------------\nDelimiter: \",\"\ndbl (2): item, location\n\ni Use `spec()` to retrieve the full column specification for this data.\ni Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# we want two dimensional data, lower off diagonal values -> stronger misfit\nsigma <- matrix(c(1, 0.15, 0.15, 1), 2)\n# a matrix to specify which dimension each item loads on\nwmat0 <- matrix(nrow = 20,\n               ncol = 2)\n# set all items to load on dimension one\nwmat0[1:20,1] <- 1\nwmat0[1:20,2] <- 0\n# item 9, with good targeting in this item set (closest to sample theta mean of 0), is chosen to belong to a second dimension\nwmat0[9,1] <- 0\nwmat0[9,2] <- 1\n\n# a matrix to specify which dimension each item loads on\nwmat1 <- matrix(nrow = 20,\n               ncol = 2)\nwmat1[1:20,1] <- 1\nwmat1[1:20,2] <- 0\nwmat1[18,1] <- 0\nwmat1[18,2] <- 1\n\n# a matrix to specify which dimension each item loads on\nwmat2 <- matrix(nrow = 20,\n               ncol = 2)\nwmat2[1:20,1] <- 1\nwmat2[1:20,2] <- 0\nwmat2[13,1] <- 0\nwmat2[13,2] <- 1\n\n# generate dichotomous data\nsimdata0 <- eRm::sim.xdim(10000, items1, cutpoint = \"randomized\", Sigma = sigma, weightmat = wmat0)\nsimdata1 <- eRm::sim.xdim(10000, items1, cutpoint = \"randomized\", Sigma = sigma, weightmat = wmat1)\nsimdata2 <- eRm::sim.xdim(10000, items1, cutpoint = \"randomized\", Sigma = sigma, weightmat = wmat2)\n\nsimdata <- list(data0 = simdata0,\n                data1 = simdata1,\n                data2 = simdata2)\n#saveRDS(simdata,\"simdata10000.rds\")\n\n### And one dataset with all 3 items misfitting\n# a matrix to specify which dimension each item loads on\nwmat3 <- matrix(nrow = 20,\n               ncol = 2)\n# set all items to load on dimension one\nwmat3[1:20,1] <- 1\nwmat3[1:20,2] <- 0\n# item 9, with good targeting in this item set (closest to sample theta mean of 0), is chosen to belong to a second dimension\nwmat3[c(9,13,18),1] <- 0\nwmat3[c(9,13,18),2] <- 1\n\n# generate dichotomous data\nsimdata3 <- eRm::sim.xdim(10000, items1, cutpoint = \"randomized\", Sigma = sigma, weightmat = wmat3)\n\n#saveRDS(simdata3,\"data/simdata3.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# simulate data using 40 items\n# read pre-generated item locations for reproducibility\nitems2 <- read_csv(\"data/rm_items40.csv\") %>%\n  pull(location)\n\n# a matrix to specify which dimension each item loads on\nwmat4 <- matrix(nrow = 40,\n               ncol = 2)\n# set all items to load on dimension one\nwmat4[1:40,1] <- 1\nwmat4[1:40,2] <- 0\n\nwmat4[c(9,13,18),1] <- 0\nwmat4[c(9,13,18),2] <- 1\n\n# generate dichotomous data\nsimdata40items <- eRm::sim.xdim(10000, items2, cutpoint = \"randomized\", Sigma = sigma, weightmat = wmat4)\n\n# check targeting\n#RItargeting(as.data.frame(simdata40items), model = \"RM\")\n#RItargeting(simdata3[,1:10], model = \"RM\")\n\n#saveRDS(simdata40items,\"data/simdata40items.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nsimdata <- readRDS(\"data/simdata10000.rds\")\n\nsimdata3 <- readRDS(\"data/simdata3.rds\") %>% \n  as.data.frame()\n\ndemodata <- simdata[[1]] %>% \n  as.data.frame() %>% \n  slice(1:400) %>% \n  select(V1,V11,V3,V12)\n\nsimdata40items <- readRDS(\"data/simdata40items.rds\") %>% \n  as.data.frame()\n```\n:::\n\n\n\n\n\n# Study 1: Item infit and outfit\n\nAssessing item fit to the Rasch model using infit and outfit was first proposed by Wright and Panchapakesan [-@wright_procedure_1969]. For a historical perspective, see Smith and colleagues [-@smith_using_1998]. Item mean square standardized residuals are either unweighted, which is referred to as \"outfit\", or information weighted, also known as \"infit\" [@ostini_polytomous_2006, pp. 86-87]. Outfit is sensitive to outliers, while infit is much less affected by outliers. Both infit and outfit are based on individual response residuals.   Conditional item infit and outfit are expected to be near 1, with higher values indicating an item to be underfitting the Rasch model (often due to multidimensionality issues) and lower values indicating overfit. For a more recent overview on item fit and its interpretation, see the book chapter by Christensen and Kreiner [-@christensen_item_2013].\n\nUnconditional item fit uses person and item parameter estimates, which results in biased residuals [@kreiner_exact_2011]. By using the total person score instead of an estimated person score, this bias can be virtually eliminated. The Rasch model describes the probability of a correct or positive response by a person to an item as:\n\n$$\nP(X_{vi} = 1) = \\frac{\\exp(\\theta_v - \\beta_i)}{1 + \\exp(\\theta_v - \\beta_i)}\n$$ {#eq-rasch}\n\nIn @eq-rasch, $X$ denotes a response, persons are indexed by $v$, items by $i$, and $\\theta$ and $\\beta$ are person and item parameters, respectively. To compute the Rasch model response residuals $Z_{vi}$, we use:\n\n$$\nZ_{vi} = \\frac{X_{vi} - E(X_{vi})}{\\sqrt{\\text{Var}(X_{vi})}}\n$$ {#eq-residuals}\n\nwhere $E(X_{vi}) = P(X_{vi} = 1)$. The formula for outfit and infit is:\n\n$$\n\\text{Outfit}_i = \\sum\\frac{Z_{vi}^2}{n}, \\quad \\text{Infit}_i = \\frac{\\sum_{v}\nZ_{v_i}^2 \\cdot w_{vi}}{\\sum_{v}w_{vi}}\n$$ {#eq-inoutfit}\n\nwhere the weights to calculate infit, $w_{vi} = \\text{Var}(X_{vi})$. Since $E(X_{vi})$ and $\\text{Var}(X_{vi})$ need to be estimated, these are replaced in the conditional fit statistics, where:\n\n$$\n\\hat{E}(X_{vi}) = \\hat{P}(X_{vi} = 1 \\mid R_v = r) = \\frac{\\exp \\left(\n-\\hat{\\beta}_i\\right) \\gamma_r{-1}\\left(\\hat{\\beta}^\\left({i}\\right) \\right) } {\\gamma_r (\\hat{\\beta)}}\n$$ {#eq-condfit}\n\n\nIn @eq-condfit, $\\hat{\\beta}$ indicates the vector of item parameters and $\\gamma_r (\\hat{\\beta})$ is \"the elementary symmetrical function of order r of the item parameter estimates\" [@muller_item_2020, p. 4]. For further details on conditional item fit we refer to the previously mentioned paper by Müller [-@muller_item_2020] and the book chapter on item fit by Christensen and Kreiner [-@christensen_item_2013].\n\nThe function `RIgetfit()` from the `easyRasch` R package is tested here. Its source code can be accessed on GitHub, see @sec-addmat. The function offers the user a choice of the number of bootstrap iterations to use to determine the critical cutoff values for each item's infit and outfit. Our main interest in this study is two-fold. We want to test variations in the number of iterations used in `RIgetfit()` and evaluate how well the critical values based on the parametric bootstrap procedure detect misfitting items. Additionally, a comparison between infit and outfit statistics in terms of detection rate and false positive rate will be conducted.\n\n20 dichotomous items are used, with one item misfitting. Item locations are the same throughout all studies unless otherwise noted. The location of the misfitting item relative to the sample theta mean was selected to be approximately 0, -1, and -2 logits. Three separate datasets were generated with these variations, each with 10 000 simulated respondents. One dataset with all three misfitting items was also generated, using the same sample size.\n\nThen the `RIitemfit()` function is used to summarize the bootstrap results and also calculates the infit and outfit for each item in the observed data and highlights items with infit/outfit values outside of the cutoff values. `RIitemfit()` has a default (user-modifiable) setting to slightly truncate the distribution of values using `stats::quantile()` at 0.001 and 0.999 to remove extreme values. An example is demonstrated in @tbl-itemfit1, using a subset of the items used in the simulations. @fig-itemfit1 provides a visualization of the distribution of bootstrapped infit and outfit values, together with the infit/outfit values from the observed data illustrated using an orange diamond shape. Note the variation between items in plausible values of infit and outfit based on the bootstrap, and that Smith's rule-of-thumb regarding infit (1±2/$\\sqrt{n}$) would be 0.9-1.1 for a sample size of 400.\n\nThis study was rather computationally demanding since each simulation run entailed 100-400 underlying bootstrap iterations. The sample sizes used were 150, 250, 500, and 1000. The number of iterations to determine cutoff values were 100, 200, and 400. Sample size and iteration conditions were fully crossed with each other and the three different targeting variations of the one misfitting item, resulting in 4 * 3 * 3 = 36 conditions. Each combination used 500 replications.\n\n\n\n\n\n::: {#tbl-itemfit1 .cell tbl-cap='Conditional item fit with simulation-based cutoff values'}\n\n```{.r .cell-code .hidden}\nsimfit <- RIgetfit(demodata, iterations = 200, cpu = 8)\nRIitemfit(demodata, simfit, output = \"quarto\")\n```\n\n::: {.cell-output-display}\n\n\n|Item | InfitMSQ|Infit thresholds | OutfitMSQ|Outfit thresholds |Infit diff |Outfit diff | Relative location|\n|:----|--------:|:----------------|---------:|:-----------------|:----------|:-----------|-----------------:|\n|V1   |    1.017|[0.901, 1.121]   |     1.061|[0.647, 1.457]    |no misfit  |no misfit   |             -1.55|\n|V11  |    1.000|[0.835, 1.166]   |     1.032|[0.723, 1.304]    |no misfit  |no misfit   |             -0.84|\n|V3   |    1.022|[0.914, 1.101]   |     1.050|[0.673, 1.479]    |no misfit  |no misfit   |              0.28|\n|V12  |    0.966|[0.874, 1.165]   |     0.793|[0.815, 1.262]    |no misfit  |0.022       |              1.40|\n\n\n:::\n:::\n\n::: {#cell-fig-itemfit1 .cell}\n\n```{.r .cell-code .hidden}\nRIgetfitPlot(simfit, demodata, output = \"both\")\n```\n\n::: {.cell-output-display}\n![Distribution of simulation-based item fit and estimated item fit from observed data](index_files/figure-pdf/fig-itemfit1-1.pdf){#fig-itemfit1 fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# define function to run simulations for item infit/outfit cutoff values\nitemfitboot <- function(dat, iterations, samplesize) {\n  \n  fit <- list()\n  fit <- foreach(i = 1:iterations) %do% {\n    data <- dat[sample(1:nrow(dat), samplesize), ] %>% \n      as.data.frame()\n    \n    # check data for responses in all cells\n    n_resp <-\n      data %>%\n      as.matrix() %>%\n      colSums2() %>%\n      t() %>%\n      as.vector()\n    \n    if (min(n_resp, na.rm = TRUE) < 11) {\n      data <- dat[sample(1:nrow(dat), samplesize), ] %>% \n        as.data.frame()\n    } \n    \n    # get simulation based cutoff values\n    sfit100 <- RIgetfit(data,100,9)\n    sfit200 <- RIgetfit(data,200,9)\n    sfit400 <- RIgetfit(data,400,9)\n\n    # apply cutoffs and store results\n    rfit100 <- RIitemfit(data,sfit100, output = \"dataframe\") %>% \n      select(infit_msq,outfit_msq,infit_diff,outfit_diff) %>% \n      add_column(item = 1:ncol(data),\n                 sims = 100,\n                 iteration = i,\n                 samplesize = samplesize)\n    \n    rfit200 <- RIitemfit(data,sfit200, output = \"dataframe\") %>% \n      select(infit_msq,outfit_msq,infit_diff,outfit_diff) %>% \n      add_column(item = 1:ncol(data),\n                 sims = 200,\n                 iteration = i,\n                 samplesize = samplesize)\n    \n    rfit400 <- RIitemfit(data,sfit400, output = \"dataframe\") %>% \n      select(infit_msq,outfit_msq,infit_diff,outfit_diff) %>% \n      add_column(item = 1:ncol(data),\n                 sims = 400,\n                 iteration = i,\n                 samplesize = samplesize)\n    \n    # combine output \n    fit <- rbind(rfit100,rfit200,rfit400)\n  }\n  return(fit)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nsamplesizes <- c(150,250,500,1000)\n\nifb0 <- list()\nifb1 <- list()\nifb2 <- list()\n\n#library(tictoc)\n#tic()\nifb0 <- map(samplesizes, ~ itemfitboot(simdata[[1]], iterations = 500, samplesize = .x))\n#toc() # 14257.358 sec elapsed\n\nifb1 <- map(samplesizes, ~ itemfitboot(simdata[[2]], iterations = 500, samplesize = .x))\nifb2 <- map(samplesizes, ~ itemfitboot(simdata[[3]], iterations = 500, samplesize = .x))\n\n# saveRDS(ifb0, \"data/ifb0_200.rds\")\n# saveRDS(ifb2, \"data/ifb2_200.rds\")\n# saveRDS(ifb1, \"data/ifb1_200.rds\")\n\nifb0_df <- map_dfr(1:4, ~ do.call(\"rbind\", ifb0[[.x]])) %>% \n  add_column(targeting = 0)\n\nifb1_df <- map_dfr(1:4, ~ do.call(\"rbind\", ifb1[[.x]])) %>% \n  add_column(targeting = 1)\n\nifb2_df <- map_dfr(1:4, ~ do.call(\"rbind\", ifb2[[.x]])) %>% \n  add_column(targeting = 2)\n\nifb <- rbind(ifb0_df,ifb1_df,ifb2_df)\n\nwrite_parquet(ifb,\"data/ifb.parquet\") \n# This code chunk was processed on three separate occasions (200+200+100 iterations) due to the time-consuming simulation.\n# This resulted in three parquet-files with results, files named ifb_part2 and ifb_part3 in addition to the filename two lines above.\n```\n:::\n\n\n\n\n\n\n## Results\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nifb <- read_parquet(\"data/ifb.parquet\")\nifb_part2 <- read_parquet(\"data/ifb_part2.parquet\") %>% \n  mutate(iteration = iteration + 200)\nifb_part3 <- read_parquet(\"data/ifb_part3.parquet\") %>% \n  mutate(iteration = iteration + 400)\n\nifb <- rbind(ifb,ifb_part2,ifb_part3)\n```\n:::\n\n\n\n\n\nFigures show the percent of simulation runs that have identified an item as misfitting. Items with more than 5% are colored in light red. A number representing the detection rate is shown adjacent to the bar representing the misfitting item. The figure grid columns are labeled with the number of iterations used by `RIgetfit()` to determine cutoff values and grid rows are labeled with the sample size.\n\nTables describing the results are available under Additional Materials, see @sec-tblinfitresults.\n\n### Infit\n\n\n\n\n\n::: {#cell-fig-ifb0 .cell}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 0) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n  ungroup() %>% \n  mutate(sims = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         samplesize = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         item = factor(item)) %>% \n  \n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"a\",\"b\"))) +\n  geom_text(data = . %>% filter(item == 9),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.3, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item', guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize~sims) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"Targeting 0 logits (item 9 misfit). 500 simulations per combination.\",\n       #title = \"Conditional infit detection rate\"\n       )\n```\n\n::: {.cell-output-display}\n![Conditional infit detection rate (misfit item at 0 logits)](index_files/figure-pdf/fig-ifb0-1.pdf){#fig-ifb0 fig-pos='H'}\n:::\n:::\n\n\n\n\n\n@fig-ifb0 shows the detection rate when the misfitting item is located at the sample mean. The detection rate is highest for the condition with 100 iterations with sample sizes 150 and 250, but it also shows higher levels of false positives when the sample size increases to 500 or more.\n\n\n\n\n\n::: {#cell-fig-ifb1 .cell}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 1) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n  ungroup() %>% \n  mutate(sims = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         samplesize = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         item = factor(item)) %>% \n  \n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"a\",\"b\"))) +\n  geom_text(data = . %>% filter(item == 18),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = 1.2, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item', guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize~sims) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"Targeting -1 logits (item 18 misfit). 500 simulations per combination.\",\n       #title = \"Conditional infit detection rate\"\n       )\n```\n\n::: {.cell-output-display}\n![Conditional infit detection rate (misfit item at -1 logits)](index_files/figure-pdf/fig-ifb1-1.pdf){#fig-ifb1 fig-pos='H'}\n:::\n:::\n\n\n\n\n\nWhen the misfitting item is offset in targeting by -1 logits compared to the sample mean (see @fig-ifb1), the smallest sample size has less power to detect misfit compared to the on-target misfitting item. There are lower rates of false positives across all sample sizes and iterations.\n\n\n\n\n\n::: {#cell-fig-ifb2 .cell}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 2) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n  ungroup() %>% \n  mutate(sims = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         samplesize = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         item = factor(item)) %>% \n  \n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"a\",\"b\"))) +\n  geom_text(data = . %>% filter(item == 13),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = 1.2, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item', guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize~sims) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"Targeting -2 logits (item 13 misfit). 500 simulations per combination.\",\n       #title = \"Conditional infit detection rate\"\n       )\n```\n\n::: {.cell-output-display}\n![Conditional infit detection rate (misfit item at -2 logits)](index_files/figure-pdf/fig-ifb2-1.pdf){#fig-ifb2 fig-pos='H'}\n:::\n:::\n\n\n\n\n\nFinally, when the misfitting item is located at -2 logits compared to the sample mean (see @fig-ifb2), we see a stronger reduction in power for sample sizes 150 and 250. No false positives are identified.\n\n### Outfit\n\n\n\n\n\n::: {#cell-fig-ifb0out .cell}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!outfit_diff == \"no misfit\",\n         targeting == 0) %>% \n  dplyr::count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n    ungroup() %>% \n  mutate(sims = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         samplesize = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         item = factor(item)) %>% \n  \n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"a\",\"b\"))) +\n  geom_text(data = . %>% filter(item == 9),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = 0, vjust = -0.3) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item', guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize~sims) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"Targeting 0 logits (item 9 misfit). 500 simulations per combination.\",\n       #title = \"Conditional outfit detection rate\"\n       )\n```\n\n::: {.cell-output-display}\n![Conditional outfit detection rate (misfit item at 0 logits)](index_files/figure-pdf/fig-ifb0out-1.pdf){#fig-ifb0out fig-pos='H'}\n:::\n:::\n\n::: {#cell-fig-ifb1out .cell}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!outfit_diff == \"no misfit\",\n         targeting == 1) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n    ungroup() %>% \n  mutate(sims = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         samplesize = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         item = factor(item)) %>% \n  \n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"a\",\"b\"))) +\n  geom_text(data = . %>% filter(item == 18),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = 1.2, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item', guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize~sims) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"Targeting -1 logits (item 18 misfit). 500 simulations per combination.\",\n       #title = \"Conditional outfit detection rate\"\n       )\n```\n\n::: {.cell-output-display}\n![Conditional outfit detection rate (misfit item at -1 logits)](index_files/figure-pdf/fig-ifb1out-1.pdf){#fig-ifb1out fig-pos='H'}\n:::\n:::\n\n::: {#cell-fig-ifb2out .cell}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!outfit_diff == \"no misfit\",\n         targeting == 2) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n    ungroup() %>% \n  mutate(sims = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         samplesize = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         item = factor(item)) %>% \n  \n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"a\",\"b\"))) +\n  geom_text(data = . %>% filter(item == 13),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.3, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item', guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize~sims) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"Targeting -2 logits (item 13 misfit). 500 simulations per combination.\",\n       #title = \"Conditional outfit detection rate\"\n       )\n```\n\n::: {.cell-output-display}\n![Conditional outfit detection rate (misfit item at -2 logits)](index_files/figure-pdf/fig-ifb2out-1.pdf){#fig-ifb2out fig-pos='H'}\n:::\n:::\n\n\n\n\n\nAs shown in @fig-ifb0out, @fig-ifb1out, and @fig-ifb2out, outfit is performing worse than infit across the board.\n\n### Comments\n\nBased on these simulation, it is highly recommended to use infit over outfit in assessing item fit. The performance of outfit calls to question whether it is useful at all for detecting item misfit.\n\nRegarding infit and the use of parametric bootstrap with the function `RIgetfit()`, it looks like 100 iterations are to recommend to determine cutoff values when the sample size is 250 or lower, while 200 or 400 iterations reduce the risk for false positives at sample sizes of 500 or larger. False positives are found at sample sizes 500 and 1000 only. The risk for false positives is notably higher when the misfitting item is located at the sample mean compared to when the misfitting item is off-target by -1 logits or more.\n\n\n# Study 2: Item-restscore\n\nItem-restscore is a metric that compares an expected correlation with the observed correlation. The \"restscore\" is the ordinal sum score from all items except the item under scrutiny. Since item data are ordinal, the marginal association between item-score and restscore is assessed using Goodman and Kruskal’s $\\gamma$ [@goodman_measures_1954;@kreiner_note_2011]. Lower observed values than expected indicate that an item is underfit to the Rasch model, while higher values indicate overfit. The item-restscore function used in this simulation is from the `iarm` package [@mueller_iarm_2022] and outputs Benjamini-Hochberg corrected *p*-values [@benjamini_controlling_1995], which are used to determine whether the differences between the observed and expected values are statistically significant, using *p* < .05 as critical value for each item. The data and procedure in this study follow the same structure as Study 1, with the addition of a smaller sample condition with 100 respondents.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nir <- function(dat, iterations, samplesize, cpu = 9) {\n  \n  require(doParallel)\n  registerDoParallel(cores = cpu)\n  \n  fit <- data.frame()\n  fit <- foreach(i = 1:iterations, .combine = rbind) %dopar% {\n    data <- dat[sample(1:nrow(dat), samplesize), ]\n    \n    erm_out <- RM(data)\n    \n    cfit <- out_infit(erm_out)\n    cfit_d <- data.frame(infit = cfit$Infit, outfit = cfit$Outfit) %>% \n      round(3)\n    \n    i1 <- item_restscore(erm_out)\n    i1 <- as.data.frame(i1)\n    \n    i1d <- data.frame(\"observed\" = as.numeric(i1[[1]][1:ncol(data),1]),\n                     \"expected\" = as.numeric(i1[[1]][1:ncol(data),2]),\n                     \"se\" = as.numeric(i1[[1]][1:ncol(data),3]),\n                     \"p.value\" = as.numeric(i1[[1]][1:ncol(data),4]),\n                     \"p.adj.BH\" = as.numeric(i1[[1]][1:ncol(data),5])\n    ) %>% \n      mutate(diff_abs = abs(expected - observed),\n             diff = expected - observed,\n             ir_padj = ifelse(p.adj.BH < .05, \"sign. misfit\",\"no misfit\")) %>% \n      select(ir_padj, diff, diff_abs) %>% \n      mutate(item = 1:ncol(data)) %>% \n      add_column(iteration = i,\n                 samplesize = samplesize)\n    cbind(i1d,cfit_d)\n  }\n  return(fit)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nsamplesizes <- c(100,150,250,500,1000)\n\nir0 <- list()\nir1 <- list()\nir2 <- list()\n#library(tictoc)\n#tic()\nir0 <- map(samplesizes, ~ ir(simdata[[1]], iterations = 1000, samplesize = .x))\nir1 <- map(samplesizes, ~ ir(simdata[[2]], iterations = 1000, samplesize = .x))\nir2 <- map(samplesizes, ~ ir(simdata[[3]], iterations = 1000, samplesize = .x))\n#toc()\n# 483.373 sec elapsed\n\nirall <- list(ir0,ir1,ir2)\n\n#saveRDS(irall,\"data/item_restscore1000.rds\")\n```\n:::\n\n\n\n\n\n## Results\n\n\n\n\n::: {#cell-fig-itemrestscore1 .cell}\n\n```{.r .cell-code .hidden}\nir_all <- readRDS(\"data/item_restscore1000.rds\")\nir_results <- bind_rows(ir_all[[1]],ir_all[[2]],ir_all[[3]]) %>% \n  add_column(targeting = rep(c(0,1,2), each = 100000))\n\n# using patchwork and separate plots to get geom_text working across targeting variations\nresults0 <- ir_results %>% \n  filter(targeting == 0) %>% \n  group_by(targeting, samplesize) %>% \n  filter(ir_padj == \"sign. misfit\" ) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/1000,\n         targeting = factor(targeting, levels = c(0,1,2), labels = c('On target','-1 logit offset','-2 logits offset')),\n         item = factor(item)) %>% \n  \n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"lightblue\",\"lightpink\"))) +\n  geom_text(data = . %>% filter(item == 9),\n            aes(label = Percent), position = position_dodge(width = 0.9),\n            hjust = -0.3, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item', guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize ~ .) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"Targeting 0 logits\") +\n  theme(strip.text = element_blank())\n\nresults1 <- ir_results %>% \n  filter(targeting == 1) %>% \n  group_by(targeting, samplesize) %>% \n  filter(ir_padj == \"sign. misfit\" ) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/1000,\n         targeting = factor(targeting, levels = c(0,1,2), labels = c('On target','1 logit offset','2 logits offset')),\n         item = factor(item)) %>%  \n  \n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"lightblue\",\"lightpink\"))) +\n  geom_text(data = . %>% filter(item == 18),\n            aes(label = n/10), position = position_dodge(width = 0.9),\n            hjust = 1.2, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item', guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize ~ .) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"Targeting -1 logits\") +\n  theme(strip.text = element_blank())\n\nresults2 <- ir_results %>% \n  filter(targeting == 2) %>% \n  group_by(targeting, samplesize) %>% \n  filter(ir_padj == \"sign. misfit\" ) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/1000,\n         targeting = factor(targeting, levels = c(0,1,2), labels = c('On target','1 logit offset','2 logits offset'))) %>% \n  mutate(samplesize = factor(samplesize, levels = c(100,150,250,500,1000),\n                       labels = c(\"n = 100\",\n                                  \"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         item = factor(item)) %>% \n  \n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"lightblue\",\"lightpink\"))) +\n  geom_text(data = . %>% filter(item == 13),\n            aes(label = n/10), position = position_dodge(width = 0.9),\n            hjust = -0.3, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item', guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize ~ .) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"Targeting -2 logits\")\n\nresults0 + results1 + results2 +\n  plot_layout(axes = \"collect\",\n              axis_titles = \"collect\") +\n  plot_annotation(#title = \"Item-restscore detection rate across targeting and sample size\",\n                  subtitle = \"1000 simulated datasets for each combination.\",\n                  theme = theme_rise(fontfamily = \"sans\"))\n```\n\n::: {.cell-output-display}\n![Item-restscore detection rate across targeting and sample size](index_files/figure-pdf/fig-itemrestscore1-1.pdf){#fig-itemrestscore1 fig-pos='H'}\n:::\n:::\n\n\n\n\n\nThis simulation includes an additional condition with 100 respondents, which results in significantly lower detection rates compared to n = 150. Compared to infit at 250 respondents, item-restscore has detection rates of 95.2%, 90.9%, and 62.4% for targeting 0, -1, and -2, while infit has 96.6%, 96.2%, and 70.6%. For sample sizes 500 and 1000, the detection rate is similar, including the increased tendency for false positives at n = 1000. The false positive rate is lower for item-restscore than infit for sample sizes below 1000.\n\nTables describing the results are available under Additional Materials, see @sec-tblirresults.\n\n# Study 3: Comparing infit and item-restscore\n\nWe will now compare the performance of infit and item-restscore when all three items are misfitting at the same time. This simulation will also include a condition with 2000 respondents to examine if the false positive rate increases with more respondents. For infit, we will use 100 iterations with `RIgetfit()` for n < 500 and 200 iterations for n >= 500 since this produced the best results in Study 1. Outfit is also included in the study, mostly to check if its' performance is similar to the condition with only one misfitting item.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# define function to run simulations for item infit/outfit cutoff values\nitemfitboot2 <- function(dat, iterations, samplesize) {\n  \n  fit <- list()\n  fit <- foreach(i = 1:iterations) %do% {\n    data <- dat[sample(1:nrow(dat), samplesize), ] %>% \n      as.data.frame()\n    \n    # check data for responses in all cells\n    n_resp <-\n      data %>%\n      as.matrix() %>%\n      colSums2() %>%\n      t() %>%\n      as.vector()\n    \n    if (min(n_resp, na.rm = TRUE) < 11) {\n      data <- dat[sample(1:nrow(dat), samplesize), ] %>% \n        as.data.frame()\n    } \n    \n    if (nrow(data < 400)) {\n      sfit <- RIgetfit(data,100,9)\n    } else if (nrow(data > 400)) {\n      sfit <- RIgetfit(data,200,9)\n    }\n    \n    # apply cutoffs and store results\n    rfit <- RIitemfit(data, sfit, output = \"dataframe\") %>% \n      select(infit_msq,outfit_msq,infit_diff,outfit_diff) %>% \n      add_column(item = 1:ncol(data),\n                 iteration = i,\n                 samplesize = samplesize)\n\n    # combine output \n    fit <- rfit\n  }\n  return(fit)\n}\n\n# using RIitemfit(cutoff = c(005,995))\nitemfitboot2b <- function(dat, iterations, samplesize) {\n  \n  fit <- list()\n  fit <- foreach(i = 1:iterations) %do% {\n    data <- dat[sample(1:nrow(dat), samplesize), ] %>% \n      as.data.frame()\n    \n    # check data for responses in all cells\n    n_resp <-\n      data %>%\n      as.matrix() %>%\n      colSums2() %>%\n      t() %>%\n      as.vector()\n    \n    if (min(n_resp, na.rm = TRUE) < 11) {\n      data <- dat[sample(1:nrow(dat), samplesize), ] %>% \n        as.data.frame()\n    } \n    \n    if (nrow(data < 400)) {\n      sfit <- RIgetfit(data,100,9)\n    } else if (nrow(data > 400)) {\n      sfit <- RIgetfit(data,200,9)\n    }\n    \n    # apply cutoffs and store results\n    rfit <- RIitemfit(data, sfit, output = \"dataframe\", cutoff = c(.005,.995)) %>% \n      select(infit_msq,outfit_msq,infit_diff,outfit_diff) %>% \n      add_column(item = 1:ncol(data),\n                 iteration = i,\n                 samplesize = samplesize)\n\n    # combine output \n    fit <- rfit\n  }\n  return(fit)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nsamplesizes <- c(150,250,500,1000,2000)\nifb3 <- list()\nir3 <- list()\n\nifb3 <- map(samplesizes, ~ itemfitboot2(simdata3, iterations = 500, samplesize = .x))\n# I initally used 200 iterations for n = 150 and n = 250, which later seemed illogical, so the next line replaces those simulations\nifb3b <- map(c(150,250), ~ itemfitboot2(simdata3, iterations = 500, samplesize = .x))\n#saveRDS(ifb3b,\"data/ifb3b.rds\")\n\nifb3c <- map(c(150,250), ~ itemfitboot2b(simdata3, iterations = 500, samplesize = .x))\n#saveRDS(ifb3c,\"data/ifb3c.rds\")\n\nir3 <- map(samplesizes, ~ ir(simdata3, iterations = 500, samplesize = .x))\n\n#saveRDS(ifb3,\"data/ifb3.rds\")\n#saveRDS(ir3,\"data/ir3.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nifb3 <- readRDS(\"data/ifb3.rds\")\nifb3b <- readRDS(\"data/ifb3b.rds\")\nifb3c <- readRDS(\"data/ifb3c.rds\")\n\nir3 <- readRDS(\"data/ir3.rds\")\n\nifb3_df <- bind_rows(ifb3)\nifb3b_df <- bind_rows(ifb3b)\n\n# filter out n = 150-250 from the simulation with 200 iterations and replace with 100 iterations\nifb3_df <- ifb3_df %>% \n  filter(!samplesize %in% c(150,250)) %>% \n  select(!sims)\n\nifb3_df <- rbind(ifb3_df,ifb3b_df)\n\nir3_df <- bind_rows(ir3)\n```\n:::\n\n\n\n\n\n### Results\n\n\n\n\n\n::: {#cell-fig-ifb3out .cell}\n\n```{.r .cell-code .hidden}\nifb3_df %>% \n  group_by(samplesize) %>% \n  filter(!outfit_diff == \"no misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\")),\n         item = factor(item)) %>% \n\n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"a\",\"b\"))) +\n  geom_text(data = . %>% filter(item == 9),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.5, vjust = 0) +\n    geom_text(data = . %>% filter(item == 13),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.5, vjust = 1) +\n    geom_text(data = . %>% filter(item == 18),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.5, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item', guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize~.) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(str_wrap(\"3 items misfitting. 200 iterations used to determine critial value. 500 simulations per combination.\",68),\n       #title = \"Conditional outfit detection rate\"\n       )\n```\n\n::: {.cell-output-display}\n![Conditional outfit detection rate with three misfitting items](index_files/figure-pdf/fig-ifb3out-1.pdf){#fig-ifb3out fig-pos='H'}\n:::\n:::\n\n::: {#cell-fig-ifb3 .cell}\n\n```{.r .cell-code .hidden}\nifb3_df %>% \n  group_by(samplesize) %>% \n  filter(!infit_diff == \"no misfit\") %>% \n  dplyr::count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\")),\n         item = factor(item)) %>% \n\n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"a\",\"b\"))) +\n  geom_text(data = . %>% filter(item == 9),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.6, vjust = 1) +\n    geom_text(data = . %>% filter(item == 13),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.6, vjust = 1) +\n    geom_text(data = . %>% filter(item == 18),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.6, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item', guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize~.) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = str_wrap(\"3 items misfitting. 500 simulations per combination.\",68),\n       #title = \"Conditional infit detection rate\"\n       )\n```\n\n::: {.cell-output-display}\n![Conditional infit detection rate with three misfitting items](index_files/figure-pdf/fig-ifb3-1.pdf){#fig-ifb3 fig-pos='H'}\n:::\n:::\n\n\n\n\n\nLooking at the performance of infit with three misfitting items (@fig-ifb3), we can see that the detection rate is markedly worse for item 13 (targeting -2 logits) in sample sizes 500 and below, compared to when single items were misfitting. The false positive rate has increased for a sample size of 1000 and we can see it increase strongly at n = 2000. Outfit (@fig-ifb3out) again performs worse than infit.\n\n\n\n\n\n::: {#cell-fig-ifb3b .cell}\n\n```{.r .cell-code .hidden}\nifb3c_df <- bind_rows(ifb3c)\n\nifb3c_df %>% \n  group_by(samplesize) %>% \n  filter(!infit_diff == \"no misfit\",\n         samplesize < 400) %>% \n  dplyr::count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\")),\n         item = factor(item)) %>% \n\n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"a\",\"b\"))) +\n  geom_text(data = . %>% filter(item == 9),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.5, vjust = 1) +\n    geom_text(data = . %>% filter(item == 13),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.5, vjust = 1) +\n    geom_text(data = . %>% filter(item == 18),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.8, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item', guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize~.) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = str_wrap(\"3 items misfitting. 500 simulations per combination. Reduced truncation of bootstrap output values.\",68),\n       #title = \"Conditional infit detection rate\"\n       )\n```\n\n::: {.cell-output-display}\n![Conditional infit detection rate with three misfitting items and increased truncation](index_files/figure-pdf/fig-ifb3b-1.pdf){#fig-ifb3b fig-pos='H'}\n:::\n:::\n\n\n\n\n\nIn @fig-ifb3b, the minimal truncation used previously to remove extreme values (quantiles .001 and .999) was increased to .005 and .995. This improves the detection rate, particularly for the n = 250 condition and item 13, but also results in an increased false positive rate.\n\n\n\n\n\n::: {#cell-fig-itemrestscore2 .cell}\n\n```{.r .cell-code .hidden}\nir3_df %>% \n  group_by(samplesize) %>% \n  filter(ir_padj == \"sign. misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/500) %>% \n  ungroup() %>% \n  mutate(item = factor(item)) %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\"))) %>% \n  \n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"lightblue\",\"lightpink\"))) +\n  geom_text(data = . %>% filter(item == 9),\n            aes(label = Percent), position = position_dodge(width = 0.9),\n            hjust = -0.5, vjust = 1) +\n    geom_text(data = . %>% filter(item == 13),\n            aes(label = Percent), position = position_dodge(width = 0.9),\n            hjust = -0.5, vjust = 1) +\n    geom_text(data = . %>% filter(item == 18),\n            aes(label = Percent), position = position_dodge(width = 0.9),\n            hjust = -0.5, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item',  guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize ~ .) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"3 items misfitting. 500 simulations per combination.\",\n       #title = \"Item-restscore detection rate\"\n       )\n```\n\n::: {.cell-output-display}\n![Item-restscore detection rate with three misfitting items](index_files/figure-pdf/fig-itemrestscore2-1.pdf){#fig-itemrestscore2 fig-pos='H'}\n:::\n:::\n\n::: {#cell-fig-comp1 .cell}\n\n```{.r .cell-code .hidden}\nifb3_sum <- ifb3_df %>% \n  group_by(samplesize) %>% \n  filter(!infit_diff == \"no misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(percent = n/500*100) %>% \n  ungroup() %>% \n  filter(item %in% c(9,13,18)) %>% \n  select(!c(n)) %>% \n  add_column(Method = \"Infit\")\n\nir3_sum <- ir3_df %>% \n  group_by(samplesize) %>% \n  filter(ir_padj == \"sign. misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(percent = n*100/500) %>% \n  ungroup() %>% \n  filter(item %in% c(9,13,18)) %>% \n  select(!n) %>% \n  add_column(Method = \"Item-restscore\")\n\nrbind(ifb3_sum,ir3_sum) %>% \n  mutate(item = factor(item, levels = c(9,18,13), labels = c(\"Item 9 (location 0)\",\n                                                          \"Item 18 (location -1)\",\n                                                          \"Item 13 (location -2)\"),\n                       ordered = T)) %>% \n    mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\"))) %>% \n\n  ggplot(aes(x = item, y = percent, fill = Method)) +\n  geom_col(position = \"dodge\") +\n  geom_text(aes(label = paste0(percent,\"%\"), y = 8), color = \"white\",\n            position = position_dodge(width = 0.9),\n            size = 3) +\n  facet_grid(samplesize ~ .) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(y = \"Detection rate in percent\",\n       #title = \"Detection rate for item-restscore compared to infit\"\n       ) +\n  scale_fill_brewer(type = \"qual\", palette = \"Dark2\") +\n  theme(axis.title.x = element_blank())\n```\n\n::: {.cell-output-display}\n![Detection rate for item-restscore compared to infit](index_files/figure-pdf/fig-comp1-1.pdf){#fig-comp1 fig-pos='H'}\n:::\n:::\n\n\n\n\n\nItem-restscore (see @fig-itemrestscore2) shows a comparable detection rate to infit and higher levels of false positives. A comparison is made between the two in @fig-comp1, where item-restscore is performing better than infit at detecting the -2 logits off-target item at n = 250, and better across all items for n = 500 and n = 1000. Infit performs better for samples n = 150 and n = 250 (except for the item with location -2 logits).\n\nTables describing the results are available under Additional Materials, see @sec-infirresults.\n\n\n\n\n\n::: {#tbl-overunder .cell tbl-cap='Item-restscore summary results across all sample sizes' tbl-colwidths='[60,40]'}\n\n```{.r .cell-code .hidden}\nir3_df %>%\n  filter(ir_padj == \"sign. misfit\") %>% \n  mutate(type = ifelse(diff < 0, \"overfit\",\"underfit\")) %>% \n  count(item,type) %>% \n  mutate(Percent = n*100/2500) %>% \n  arrange(desc(Percent)) %>% \n  select(!n) %>% \n  set_names(c(\"Item\",\"Type of misfit\",\"Percent\")) %>% \n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n| Item|Type of misfit | Percent|\n|----:|:--------------|-------:|\n|    9|underfit       |   85.28|\n|   18|underfit       |   78.96|\n|   13|underfit       |   63.80|\n|    2|overfit        |   20.80|\n|    6|overfit        |   19.00|\n|   20|overfit        |   15.48|\n|    8|overfit        |   15.28|\n|   10|overfit        |   14.60|\n|   11|overfit        |   13.04|\n|    7|overfit        |   12.52|\n|   15|overfit        |   12.52|\n|    1|overfit        |   11.96|\n|    5|overfit        |   11.92|\n|   16|overfit        |   11.12|\n|    3|overfit        |    8.96|\n|   14|overfit        |    7.28|\n|    4|overfit        |    7.24|\n|   12|overfit        |    5.96|\n|   17|overfit        |    5.16|\n|   19|overfit        |    1.24|\n|   12|underfit       |    0.08|\n\n\n:::\n:::\n\n\n\n\n\nReviewing the type of misfit identified by item-restscore (see @tbl-overunder), the false positives are all overfitting the Rasch model, except for two instances (out of 2500) indicating underfit for item 12. Items 9, 13, and 18, which were simulated to be misfitting due to loading on a separate dimension, are as expected showing underfit to the Rasch model.\n\n# Study 4: Bootstrapped item-restscore\n\nFor this set of simulations, we will use a non-parametric bootstrap procedure with item-restscore. The difference from the parametric bootstrap is that the non-parametric bootstrap samples with replacement directly from the observed response data. First, based on the above problematic sample size of 2000 when three items are misfitting, we will use the bootstrap function to sample with replacement using n = 800 and 250 bootstrap samples. The function `RIbootRestscore()` from the `easyRasch` package will be used. \n\nSecond, we will also apply the bootstrapped item-restscore method to sample sizes 150 and 250, using the complete sample for the same bootstrap procedure to see if this produces more useful information than previously tested strategies for identifying misfitting items.\n\n## Results\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nir_boot <- function(dat, iterations, samplesize) {\n  \n  fit <- list()\n  fit <- foreach(i = 1:iterations) %do% {\n    data <- dat[sample(1:nrow(dat), samplesize), ] %>% \n      as.data.frame()\n    \n    fit <- RIbootRestscore(data, iterations = 250, samplesize = 800, cpu = 9, output = \"dataframe\", cutoff = 0) %>% \n      select(item,item_restscore,percent) %>% \n      filter(!item_restscore == \"no misfit\") %>% \n      add_column(iteration = i)\n    \n  }\n  return(fit)\n}\n\nirb0 <- ir_boot(simdata3, 500, 2000)\nsaveRDS(irb0,\"data/irb0.rds\")\n```\n:::\n\n::: {#cell-fig-irb0all .cell}\n\n```{.r .cell-code .hidden}\nirb0 <- readRDS(\"data/irb0.rds\")\n\nirb0_df <- bind_rows(irb0)\n\n# irb0_df %>% \n#   mutate(item = factor(item, levels = paste0(\"V\",20:1), ordered = T)) %>% \n#   ggplot(aes(x = percent, y = item, color = item_restscore)) +\n#   stat_pointinterval(point_interval\t= \"median_hdci\") +\n#   theme_rise(fontfamily = \"sans\") +\n#   labs(caption = str_wrap(\"Point indicates median value and lines are highest-density continuous interval for .66 and .95.\",80),\n#        x = \"Distribution of percent values for item misfit\", y = \"Item\",\n#        title = \"Item-restscore bootstrap results\",\n#        subtitle = str_wrap(\"250 bootstrap iterations with 800 respondents from a sample of 2000. 500 simulations were used.\",70)\n#        ) +\n#   scale_color_discrete('Type', labels = c(\"Overfit\",\"Underfit\"))\n\nirb0_df %>% \n  mutate(item = factor(item, levels = paste0(\"V\",20:1), ordered = T)) %>% \n  group_by(item,item_restscore) %>% \n  summarise(median = median(percent),\n            mean = mean(percent),\n            q_lower = quantile(percent, .05),\n            q_upper = quantile(percent, .95),\n            sd = sd(percent),\n            mad = mad(percent),\n            se = sd(percent) / sqrt(500),\n            ci_upper = median + (1.96*se),\n            ci_lower = median - (1.96*se)) %>% \n  \n  ggplot(aes(x = median, y = item, color = item_restscore)) +\n  geom_point(size = 3.5, shape = 18) +\n  geom_segment(aes(x = median - mad, xend = median + mad)) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(caption = str_wrap(\"Point indicates median value and horizontal lines are median absolute deviation.\",80),\n       x = \"Distribution of percent values for item misfit\", y = \"Item\",\n       #title = \"Item-restscore bootstrap results\",\n       subtitle = str_wrap(\"250 bootstrap iterations with 800 respondents from a sample of 2000. 500 simulations were used.\",70)\n       ) +\n  scale_color_discrete('Type', labels = c(\"Overfit\",\"Underfit\"))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`summarise()` has grouped output by 'item'. You can override using the\n`.groups` argument.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Item-restscore bootstrap results (n = 2000)](index_files/figure-pdf/fig-irb0all-1.pdf){#fig-irb0all fig-pos='H'}\n:::\n:::\n\n::: {#tbl-irb0mis .cell layout-ncol=\"1\" tbl-cap='Summary statistics for item-restscore bootstrap simulation' tbl-subcap='[\"Misfitting items\",\"False positives\"]'}\n\n```{.r .cell-code .hidden}\nirb0_df %>% \n  filter(item %in% c(\"V9\",\"V13\",\"V18\")) %>% \n  rename(Item = item) %>% \n  group_by(Item) %>% \n  summarise(Median = median(percent),\n            MAD = mad(percent),\n            Mean = mean(percent),\n            SD = sd(percent),\n            `Percentile .05` = quantile(percent, .05)\n            ) %>% \n  ungroup() %>% \n  arrange(desc(`Percentile .05`)) %>% \n  mutate_if(is.numeric, round, 1) %>% \n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | Median| MAD|  Mean|  SD| Percentile .05|\n|:----|------:|---:|-----:|---:|--------------:|\n|V9   |  100.0| 0.0| 100.0| 0.1|          100.0|\n|V18  |  100.0| 0.0|  99.8| 0.9|           99.2|\n|V13  |   95.6| 4.7|  93.0| 8.0|           76.4|\n\n\n:::\n\n```{.r .cell-code .hidden}\nirb0_df %>% \n  filter(!item %in% c(\"V9\",\"V13\",\"V18\"),\n         item_restscore == \"overfit\") %>% \n  rename(Item = item) %>% \n  group_by(Item) %>% \n  summarise(Median = median(percent),\n            MAD = mad(percent),\n            Mean = mean(percent),\n            SD = sd(percent),\n            `Percentile .95` = quantile(percent, .95)\n            ) %>% \n  ungroup() %>% \n  arrange(desc(`Percentile .95`)) %>% \n  mutate_if(is.numeric, round, 1) %>% \n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | Median|  MAD| Mean|   SD| Percentile .95|\n|:----|------:|----:|----:|----:|--------------:|\n|V2   |   20.0| 15.4| 24.3| 16.7|           58.8|\n|V6   |   18.4| 14.2| 21.3| 14.9|           52.8|\n|V8   |   14.4| 12.5| 19.7| 15.6|           51.6|\n|V11  |   14.0| 11.9| 17.6| 13.9|           47.7|\n|V15  |   13.2| 10.1| 16.6| 13.4|           45.2|\n|V20  |   16.4| 13.6| 19.5| 13.9|           45.2|\n|V5   |   12.0| 10.1| 15.7| 12.6|           44.4|\n|V10  |   13.2| 11.3| 16.4| 13.0|           42.4|\n|V16  |   11.4| 10.4| 15.2| 13.0|           42.0|\n|V7   |   13.2| 11.9| 16.7| 12.6|           41.6|\n|V1   |   12.0| 10.1| 15.5| 12.8|           41.3|\n|V3   |   10.8|  9.5| 13.6| 11.2|           36.1|\n|V14  |    7.2|  6.5| 10.4| 10.1|           30.7|\n|V12  |    7.6|  7.7| 10.4|  9.5|           29.7|\n|V4   |    7.2|  6.5| 10.2|  9.5|           29.3|\n|V17  |    6.4|  6.5|  8.4|  8.0|           24.4|\n|V19  |    2.4|  2.4|  3.9|  4.6|           13.6|\n\n\n:::\n:::\n\n\n\n\n\n@fig-irb0all shows that there is variation in the false positive rate and it is nearly always indicating overfit, while the misfitting items are only indicated as underfit. The summary statistics in @tbl-irb0mis show that there can be quite a bit of variation for false positives, but the clear majority of results are below 50%. 3 items have 95th percentile values above 50, with the highest at 58.8.\n\n## Small sample (n = 150)\n\nWe will use 200 simulations to check the performance of the bootstrapped item-restscore function for sample size 150. As an additional experimental condition, we will use both 250 and 500 bootstrap iterations for item-restscore in each simulation.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nir_boot2 <- function(dat, iterations, samplesize) {\n  \n  fit <- list()\n  fit <- foreach(i = 1:iterations) %do% {\n    data <- dat[sample(1:nrow(dat), samplesize), ] %>% \n      as.data.frame()\n    \n        # check data for responses in all cells\n    n_resp <-\n      data %>%\n      as.matrix() %>%\n      colSums2() %>%\n      t() %>%\n      as.vector()\n    \n    if (min(n_resp, na.rm = TRUE) < 11) {\n      data <- dat[sample(1:nrow(dat), samplesize), ] %>% \n        as.data.frame()\n    } \n    \n    fit1 <- RIbootRestscore(data, iterations = 250, samplesize = nrow(data), cpu = 9, output = \"dataframe\", cutoff = 0) %>% \n      select(item,item_restscore,percent) %>% \n      filter(!item_restscore == \"no misfit\") %>% \n      add_column(iteration = i,\n                 bootit = 250)\n    \n    fit2 <- RIbootRestscore(data, iterations = 500, samplesize = nrow(data), cpu = 9, output = \"dataframe\", cutoff = 0) %>% \n      select(item,item_restscore,percent) %>% \n      filter(!item_restscore == \"no misfit\") %>% \n      add_column(iteration = i,\n                 bootit = 500)\n    \n    fit <- rbind(fit1,fit2)\n    \n  }\n  return(fit)\n}\n\nirb150 <- ir_boot2(simdata3, 200, 150)\nsaveRDS(irb150,\"data/irb150.rds\")\n\n# irb250 <- ir_boot2(simdata3, 200, 250)\n# saveRDS(irb250,\"data/irb250.rds\")\n```\n:::\n\n::: {#cell-fig-irboot150 .cell}\n\n```{.r .cell-code .hidden}\nirb150 <- readRDS(\"data/irb150.rds\")\n\nirb150_df <- bind_rows(irb150)\n\nirb150_df %>% \n  mutate(item = factor(item, levels = paste0(\"V\",20:1), ordered = T),\n         bootit = factor(bootit, levels = c(250,500),\n                         labels = c(\"250 bootstrap iterations\",\n                                    \"500 bootstrap iterations\"))) %>% \n  group_by(item,item_restscore,bootit) %>% \n  summarise(median = median(percent),\n            mean = mean(percent),\n            q_lower = quantile(percent, .05),\n            q_upper = quantile(percent, .95),\n            sd = sd(percent),\n            mad = mad(percent),\n            se = sd(percent) / sqrt(500),\n            ci_upper = median + (1.96*se),\n            ci_lower = median - (1.96*se)) %>% \n  \n  ggplot(aes(x = median, y = item, color = item_restscore)) +\n  geom_point(size = 3.5, shape = 18) +\n  geom_segment(aes(x = median - mad, xend = median + mad)) +\n    geom_text(data = . %>% filter(item == \"V9\",\n                                  item_restscore == \"underfit\"),\n            aes(label = median), color = \"black\",\n            hjust = -0.1, vjust = -1) +\n    geom_text(data = . %>% filter(item == \"V13\",\n                                  item_restscore == \"underfit\"),\n            aes(label = median), color = \"black\",\n            hjust = -0.1, vjust = -1) +\n    geom_text(data = . %>% filter(item == \"V18\",\n                                  item_restscore == \"underfit\"),\n            aes(label = median), color = \"black\",\n            hjust = -0.1, vjust = -1) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(caption = str_wrap(\"Point indicates median value and horizontal lines are median absolute deviation.\",80),\n       x = \"Distribution of percent values for item misfit\", y = \"Item\",\n       #title = \"Item-restscore bootstrap results\",\n       subtitle = str_wrap(\"250 bootstrap iterations with 800 respondents from a sample of 2000. 500 simulations were used.\",70)\n       ) +\n  scale_color_discrete('Type', labels = c(\"Overfit\",\"Underfit\")) +\n  facet_wrap(~bootit)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`summarise()` has grouped output by 'item', 'item_restscore'. You can override\nusing the `.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# irb150_df %>% \n#   mutate(bootit = factor(bootit, levels = c(250,500),\n#                          labels = c(\"250 bootstrap iterations\",\n#                                     \"500 bootstrap iterations\"))) %>% \n#   ggplot(aes(x = percent, y = item, color = item_restscore)) +\n#   stat_pointinterval(point_interval\t= \"median_hdci\") +\n#   theme_rise(fontfamily = \"sans\") +\n#   labs(caption = str_wrap(\"Point indicates median value and lines are highest-density continuous interval for .66 and .95.\",80),\n#        x = \"Distribution of percent values for item misfit\", y = \"Item\",\n#        title = \"Item-restscore bootstrap results\",\n#        subtitle = str_wrap(\"250 and 500 bootstrap iterations with 150 respondents from a sample of 150. 200 simulations were used.\",70)\n#        ) +\n#   scale_color_discrete('Type', labels = c(\"Overfit\",\"Underfit\")) +\n#   facet_wrap(~bootit)\n```\n\n::: {.cell-output-display}\n![Item-restscore bootstrap results (n = 150)](index_files/figure-pdf/fig-irboot150-1.pdf){#fig-irboot150 fig-pos='H'}\n:::\n:::\n\n\n\n\n\nItem-restscore bootstrapping improves slightly on the single instance of item-restscore for the n = 150 condition (see @fig-irboot150). When comparing to the previous results in @fig-itemrestscore2, where the detection rate for the same sample size was at 49.2%, 14.6%, and 34.6% (for items 9, 13, and 18 respectively), the corresponding median values from the bootstrapped item-restscore with 250 iterations were 52.4%, 19.2%, and 38.4%. Using 500 bootstrap iterations did not result in relevant improvements over 250 iterations (see @tbl-irb150mis). Compared to the results using infit (@fig-ifb3), with detection rates of 59.2%, 19%, and 51.8%, item-restscore inferior also when bootstrapped.\n\n\n\n\n\n::: {#tbl-irb150mis .cell tbl-cap='Summary statistics for item-restscore bootstrap simulation (n = 150)'}\n\n```{.r .cell-code .hidden}\nirb150_tbl <- irb150_df %>% \n  filter(item %in% c(\"V9\",\"V13\",\"V18\"),\n         item_restscore == \"underfit\") %>% \n  rename(Item = item) %>% \n  group_by(Item,bootit) %>% \n  summarise(Median = median(percent),\n            MAD = mad(percent),\n            Mean = mean(percent),\n            SD = sd(percent)\n            ) %>% \n  ungroup() %>% \n  arrange(bootit,desc(Median)) %>% \n  mutate_if(is.numeric, round, 1) %>% \n  mutate(bootit = as.character(bootit)) %>% \n  relocate(bootit, .before = \"Item\") %>% \n  rename(`Bootstrap iterations` = bootit)  \n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`summarise()` has grouped output by 'Item'. You can override using the\n`.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nirb150_tbl[c(1,3,4,6),1] <- \"\"\n\nknitr::kable(irb150_tbl)\n```\n\n::: {.cell-output-display}\n\n\n|Bootstrap iterations |Item | Median|  MAD| Mean|   SD|\n|:--------------------|:----|------:|----:|----:|----:|\n|                     |V9   |   52.4| 38.0| 51.4| 29.2|\n|250                  |V18  |   38.4| 35.6| 42.0| 27.8|\n|                     |V13  |   19.2| 21.9| 27.3| 25.0|\n|                     |V9   |   54.3| 37.8| 51.0| 29.5|\n|500                  |V18  |   37.2| 35.9| 41.4| 27.9|\n|                     |V13  |   19.4| 23.1| 27.2| 24.7|\n\n\n:::\n:::\n\n\n\n\n\n\n# Study 5: Varying the number of items \n\nFor this simulation, we will vary the number of items and the number of misfitting items. First, 40 dichotomous items will be used, adding 20 new item locations to the previously used set, with the same three items misfitting (items 9, 13, and 18). Second, items 1-10 out of the initial 20 items will be used, which means only item 9 will be misfit. We'll again be using sample sizes of 150, 250, 500, and 1000.\n\nItem-restscore and item infit will be compared. The latter will use 100 bootstrap iterations to determine critical values for sample sizes 150 and 250, and 200 bootstrap iterations for n >= 500.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nsamplesizes <- c(150,250,500,1000)\nifb10 <- list()\nir10 <- list()\n\n#tic()\nifb40_60 <- map(samplesizes, ~ itemfitboot2(simdata40items, iterations = 60, samplesize = .x))\n#toc() # 120s for 2 runs\nsaveRDS(ifb40_60, \"data/ifb40_60i.rds\")\n\nifb40_140 <- map(samplesizes, ~ itemfitboot2(simdata40items, iterations = 140, samplesize = .x))\n#toc() # 120s for 2 runs\nsaveRDS(ifb40_140, \"data/ifb40_140i.rds\")\n\nifb10 <- map(samplesizes, ~ itemfitboot2(simdata3[,1:10], iterations = 200, samplesize = .x))\n\nsaveRDS(ifb10, \"data/ifb10.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nir40 <- map(samplesizes, ~ ir(simdata40items, iterations = 500, samplesize = .x))\nsaveRDS(ir40, \"data/ir40.rds\")\n\nir10 <- map(samplesizes, ~ ir(simdata3[,1:10], iterations = 500, samplesize = .x))\nsaveRDS(ir10, \"data/ir10.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nir40 <- readRDS(\"data/ir40.rds\")\nir10 <- readRDS(\"data/ir10.rds\")\n\nifb40_60 <- readRDS(\"data/ifb40_60i.rds\")\nifb40_140 <- readRDS(\"data/ifb40_140i.rds\")\nifb10 <- readRDS(\"data/ifb10.rds\")\n\n\nir40_df <- bind_rows(ir40)\nir10_df <- bind_rows(ir10)\n\nifb40_60_df <- bind_rows(ifb40_60)\nifb40_140_df <- bind_rows(ifb40_140)\nifb40_df <- rbind(ifb40_60_df,ifb40_140_df)\n\nifb10_df <- bind_rows(ifb10)\n```\n:::\n\n\n\n\n\n## Results 40 items\n\n\n\n\n\n::: {#cell-fig-ifb40 .cell}\n\n```{.r .cell-code .hidden}\nifb40_df %>% \n  group_by(samplesize) %>% \n  filter(!infit_diff == \"no misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = round(n/200*100,1)) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\"))) %>% \n\n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"a\",\"b\"))) +\n  geom_text(data = . %>% filter(item == 9),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.3, vjust = 1) +\n    geom_text(data = . %>% filter(item == 13),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.3, vjust = 1) +\n    geom_text(data = . %>% filter(item == 18),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = -0.3, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_continuous('Item', limits = c(1,40), breaks = seq(1,40,1), guide = guide_axis(n.dodge = 2), minor_breaks = NULL) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize~.) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"3 items misfitting. 200 simulations per combination.\",\n       #title = \"Conditional infit detection rate\"\n       )\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 8 rows containing missing values or values outside the scale range\n(`geom_col()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Conditional infit detection rate with 40 items (3 misfit)](index_files/figure-pdf/fig-ifb40-1.pdf){#fig-ifb40 fig-pos='H'}\n:::\n:::\n\n::: {#cell-fig-itemrestscore40 .cell}\n\n```{.r .cell-code .hidden}\nir40_df %>% \n  group_by(samplesize) %>% \n  filter(ir_padj == \"sign. misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/500) %>% \n  ungroup() %>% \n  mutate(item = factor(item)) %>% \n  \n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"lightblue\",\"lightpink\"))) +\n  geom_text(data = . %>% filter(item == 9),\n            aes(label = Percent), position = position_dodge(width = 0.9),\n            hjust = -0.3, vjust = 1) +\n    geom_text(data = . %>% filter(item == 13),\n            aes(label = Percent), position = position_dodge(width = 0.9),\n            hjust = -0.3, vjust = 1) +\n    geom_text(data = . %>% filter(item == 18),\n            aes(label = Percent), position = position_dodge(width = 0.9),\n            hjust = -0.3, vjust = 1) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item', \n                     guide = guide_axis(n.dodge = 2)) +\n  guides(fill = \"none\") +\n  facet_grid(samplesize ~ .) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"3 items misfitting. 500 simulations per combination.\",\n       #title = \"Item-restscore detection rate\"\n       )\n```\n\n::: {.cell-output-display}\n![Item-restscore detection rate with 40 items (3 misfit)](index_files/figure-pdf/fig-itemrestscore40-1.pdf){#fig-itemrestscore40 fig-pos='H'}\n:::\n:::\n\n\n\n\n\nInfit performs better when the sample size is 150 or 250 (see @fig-ifb40), while performance is slightly better for item-restscore for n >= 500 in terms of lower rates of false positives (see @fig-itemrestscore40).\n\n## Results 10 items\n\n\n\n\n\n::: {#cell-fig-ifb10 .cell}\n\n```{.r .cell-code .hidden}\nifb10_df %>% \n  group_by(samplesize) %>% \n  filter(!infit_diff == \"no misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = round(n/200*100,1)) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\"))) %>% \n  mutate(item = factor(item)) %>% \n\n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"a\",\"b\"))) +\n  geom_text(data = . %>% filter(item == 9),\n            aes(label = Percent), \n            position = position_dodge(width = 0.9),\n            hjust = 0.5, vjust = 1.5) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete('Item') +\n  guides(fill = \"none\") +\n  facet_grid(samplesize ~ .) +\n  coord_cartesian(clip = \"off\") +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"Item 9 misfitting (targeting = 0). 200 simulations per combination.\",\n       #title = \"Conditional infit detection rate\"\n       )\n```\n\n::: {.cell-output-display}\n![Conditional infit detection rate (10 items)](index_files/figure-pdf/fig-ifb10-1.pdf){#fig-ifb10 fig-pos='H'}\n:::\n:::\n\n::: {#cell-fig-itemrestscore10 .cell}\n\n```{.r .cell-code .hidden}\nir10_df %>% \n  group_by(samplesize) %>% \n  filter(ir_padj == \"sign. misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/500) %>% \n  ungroup() %>% \n  mutate(item = factor(item)) %>% \n  \n  ggplot(aes(x = item, y = Percent)) +\n  geom_col(aes(fill = ifelse(Percent > 5, \"a\",\"b\"))) +\n  geom_text(data = . %>% filter(item == 9),\n            aes(label = Percent), position = position_dodge(width = 0.9),\n            hjust = 0.5, vjust = 1.5) +\n  scale_y_continuous(limits = c(0,105), breaks = seq(0,100,25)) +\n  scale_x_discrete() +\n  guides(fill = \"none\") +\n  facet_grid(samplesize ~ .) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(subtitle = \"Item 9 misfitting (targeting = 0). 500 simulations per combination.\",\n       #title = \"Item-restscore detection rate\",\n       x = \"Item\")\n```\n\n::: {.cell-output-display}\n![Item-restscore detection rate (10 items)](index_files/figure-pdf/fig-itemrestscore10-1.pdf){#fig-itemrestscore10 fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n## Summary figure\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nifb20sum <- ifb3_df %>% \n  group_by(samplesize) %>% \n  filter(!infit_diff == \"no misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = round(n/500*100,1)) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\"))) %>% \n  mutate(item = factor(item)) %>% \n  select(!n) %>% \n  add_column(n_items = 20)\n\nifb40sum <- ifb40_df %>% \n  group_by(samplesize) %>% \n  filter(!infit_diff == \"no misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = round(n/200*100,1)) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\"))) %>% \n  mutate(item = factor(item)) %>% \n  select(!n) %>% \n  add_column(n_items = 40)\n\nifb_k <- rbind(ifb20sum,ifb40sum) %>% \n  add_column(Method = \"Conditional infit\")\n\n\n\nir20sum <- ir3_df %>% \n  group_by(samplesize) %>% \n  filter(ir_padj == \"sign. misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/500) %>% \n  ungroup() %>% \n  mutate(item = factor(item)) %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\"))) %>% \n  select(!n) %>% \n  add_column(n_items = 20)\n\nir40sum <- ir40_df %>% \n  group_by(samplesize) %>% \n  filter(ir_padj == \"sign. misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/500) %>% \n  ungroup() %>% \n  mutate(item = factor(item)) %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\"))) %>% \n  select(!n) %>% \n  add_column(n_items = 40)\n\nir_k <- rbind(ir20sum,ir40sum) %>% \n  add_column(Method = \"Item-restscore\")\n\ndfk2040 <- rbind(ifb_k,ir_k)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# 10 and 20 items separately with one misfitting item\nir10sum <- ir10_df %>% \n  group_by(samplesize) %>% \n  filter(ir_padj == \"sign. misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/500) %>% \n  ungroup() %>% \n  mutate(item = factor(item)) %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\"))) %>% \n  select(!n) %>% \n  add_column(n_items = 10)\n\nir20sum2 <- ir_results %>% \n  filter(targeting == 0,\n         !samplesize == 100) %>% \n  group_by(targeting, samplesize) %>% \n  filter(ir_padj == \"sign. misfit\" ) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/1000) %>% \n  ungroup() %>% \n  mutate(item = factor(item)) %>% \n  select(!c(targeting,n)) %>% \n    mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\"))) %>% \n  add_column(n_items = 20)\n\n\nifb10sum <- ifb10_df %>% \n  group_by(samplesize) %>% \n  filter(!infit_diff == \"no misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = round(n/200*100,1)) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\"))) %>% \n  mutate(item = factor(item)) %>% \n  select(!n) %>% \n  add_column(n_items = 10)\n\nifb20_1 <- ifb %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 0) %>% \n  filter(samplesize %in% c(150,250) & sims == 100) %>% \n  group_by(samplesize) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\")),\n         item = factor(item)) %>% \n  select(!n) %>% \n  add_column(n_items = 20)\n\nifb20_2 <- ifb %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 0) %>% \n  filter(samplesize %in% c(500,1000) & sims == 200) %>% \n  group_by(samplesize) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\")),\n         item = factor(item)) %>% \n  select(!n) %>% \n  add_column(n_items = 20)\n\ndfk10 <- rbind(ifb10sum,ifb20_1,ifb20_2) %>% \n  add_column(Method = \"Conditional infit\")\n\ndfk10_2 <- rbind(ir10sum,ir20sum2) %>% \n        add_column(Method = \"Item-restscore\")\n\n\ndfk10 <- rbind(dfk10,dfk10_2)\n```\n:::\n\n::: {#cell-fig-comp10 .cell}\n\n```{.r .cell-code .hidden}\ndfk10 %>% \n  mutate(item = as.numeric(item)) %>% \n  filter(item %in% c(9),\n         !samplesize %in% c(\"n = 2000\")) %>% \n  drop_na(samplesize) %>% \n  mutate(item = factor(item, levels = c(9,18,13), labels = c(\"Item 9 (location 0)\",\n                                                             \"Item 18 (location -1)\",\n                                                             \"Item 13 (location -2)\"),\n                       ordered = T),\n         n_items = factor(n_items, levels = c(10,20), labels = c(\"10 items\",\"20 items\"))) %>% \n\n  ggplot(aes(x = item, y = Percent, fill = Method)) +\n  geom_col(position = \"dodge\") +\n  geom_text(aes(label = paste0(Percent,\"%\"), y = 8), color = \"white\",\n            position = position_dodge(width = 0.9),\n            size = 3.3) +\n  facet_grid(samplesize ~ n_items) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(y = \"Detection rate in percent\",\n       #title = \"Detection rate for item-restscore and infit across sample sizes\",\n       subtitle = \"One item misfitting with location = 0 logits compared to sample mean.\") +\n  scale_fill_brewer(type = \"qual\", palette = \"Dark2\") +\n  theme(axis.title.x = element_blank())\n```\n\n::: {.cell-output-display}\n![Detection rate for item-restscore and infit for 10 items](index_files/figure-pdf/fig-comp10-1.pdf){#fig-comp10 fig-pos='H'}\n:::\n:::\n\n::: {#cell-fig-comp2040 .cell}\n\n```{.r .cell-code .hidden}\ndfk2040 %>% \n  mutate(item = as.numeric(item)) %>% \n  filter(item %in% c(9,18,13),\n         !samplesize %in% c(\"n = 2000\")) %>% \n  drop_na(samplesize) %>% \n  mutate(item = factor(item, levels = c(9,18,13), labels = c(\"Item 9 (location 0)\",\n                                                          \"Item 18 (location -1)\",\n                                                          \"Item 13 (location -2)\"),\n                       ordered = T),\n         n_items = factor(n_items, levels = c(20,40), labels = c(\"20 items\",\"40 items\"))) %>% \n  mutate(Method = factor(Method, labels = c(\"Conditional\\ninfit\",\"Item-\\nrestscore\"))) %>% \n\n  ggplot(aes(x = item, y = Percent, fill = Method)) +\n  geom_col(position = \"dodge\") +\n  geom_text(aes(label = paste0(Percent,\"%\"), y = 8), color = \"white\",\n            position = position_dodge(width = 0.9),\n            size = 2.7) +\n  facet_grid(samplesize ~ n_items) +\n  theme_rise(fontfamily = \"sans\") +\n  labs(y = \"Detection rate in percent\",\n       #title = \"Detection rate for item-restscore and infit across sample sizes and number of items\",\n       subtitle = \"Three items misfitting.\") +\n  scale_fill_brewer(type = \"qual\", palette = \"Dark2\") +\n  scale_x_discrete(guide = guide_axis(n.dodge = 2)) +\n  theme(axis.title.x = element_blank())\n```\n\n::: {.cell-output-display}\n![Detection rate for item-restscore and infit for 20 and 40 items](index_files/figure-pdf/fig-comp2040-1.pdf){#fig-comp2040 fig-pos='H'}\n:::\n:::\n\n\n\n\n\n@fig-comp10 and @fig-comp2040 summarize the findings from the two different comparisons of item numbers.  Adding more items improves the detection rate substantially for both methods, particularly for smaller samples and the off-target items. 40 items compared to 20 items result in a larger improvement for infit over item-restscore for the n = 150 condition, but also the n = 250 and n = 500 conditions for the -2 logits off-target item.\n\n# Study 6: Conditional likelihood ratio test\n\nWhile global tests of model fit don't provide any information about reasons for misfit when detected, they can be useful together with more specific tests such as those demonstrated in this paper. A commonly used global goodness-of-fit test is the Likelihood Ratio Test [LRT, @andersen_goodness_1973], which is also implemented in the `eRm` package. While the global test is not central to the purposes of this paper (detecting item misfit), it could provide readers with a familiar test as a reference and perhaps aid the item-focused methods in determining misfit. Previous simulation studies evaluating the LRT have found it to not be sensitive to detect multidimensionality [@debelak_evaluation_2019].\n\nFor this simulation, sample sizes were set to 150, 250, 500, 1000, and 2000, using 1000 simulations for each condition. Study 6 follows the previous procedures. First, the three datasets with one misfitting item out of 20, varying the misfitting items location (0, -1, and -2 logits). Then the datasets with three misfitting items, and comparing 20 and 40 items. And finally, one dataset with 10 items and one well-targeted misfitting item.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlrtsim <- function(dat, iterations, samplesize, cpu = 9) {\n  \n  require(doParallel)\n  registerDoParallel(cores = cpu)\n  \n  fit <- data.frame()\n  fit <- foreach(i = 1:iterations, .combine = rbind) %dopar% {\n    data <- dat[sample(1:nrow(dat), samplesize), ]\n    \n    erm_out <- RM(data)\n    lrt <- LRtest(erm_out)\n    data.frame(p = lrt[[\"pvalue\"]],\n               n = samplesize)\n    # same p-values with clr_tests()\n    #clr <- clr_tests(dat.items = data, model = \"RM\")\n    #clr[,3]\n    \n  }\n  return(fit)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nsamplesizes <- c(150,250,500,1000,2000)\n\n# single misfit item\nlrt0 <- map(samplesizes, ~ lrtsim(simdata[[1]], iterations = 1000, samplesize = .x))\nlrt1 <- map(samplesizes, ~ lrtsim(simdata[[1]], iterations = 1000, samplesize = .x))\nlrt2 <- map(samplesizes, ~ lrtsim(simdata[[1]], iterations = 1000, samplesize = .x))\n\n# one misfit amongst 10\nlrt10 <- map(samplesizes, ~ lrtsim(simdata3[,1:10], iterations = 1000, samplesize = .x))\n# 3 misfit items\nlrt20 <- map(samplesizes, ~ lrtsim(simdata3, iterations = 1000, samplesize = .x))\nlrt40 <- map(samplesizes, ~ lrtsim(simdata40items, iterations = 1000, samplesize = .x))\n\nsaveRDS(lrt0,\"data/lrt0.rds\")\nsaveRDS(lrt1,\"data/lrt1.rds\")\nsaveRDS(lrt2,\"data/lrt2.rds\")\nsaveRDS(lrt10,\"data/lrt10.rds\")\nsaveRDS(lrt20,\"data/lrt20.rds\")\nsaveRDS(lrt40,\"data/lrt40.rds\")\n```\n:::\n\n\n\n\n\n## Results\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlrt0_df <- readRDS(\"data/lrt0.rds\") %>% \n  bind_rows() %>% \n  select(!i) %>% \n  rename(samplesize = n) %>% \n  add_column(targeting = 0)\nlrt1_df <- readRDS(\"data/lrt1.rds\") %>% \n  bind_rows() %>% \n  select(!i) %>% \n  rename(samplesize = n) %>% \n  add_column(targeting = 1)\nlrt2_df <- readRDS(\"data/lrt2.rds\") %>% \n  bind_rows() %>% \n  select(!i) %>% \n  rename(samplesize = n) %>% \n  add_column(targeting = 2)\n\nlrt10_df <- readRDS(\"data/lrt10.rds\") %>% \n  bind_rows() %>% \n  select(!i) %>% \n  rename(samplesize = n) %>% \n  add_column(n_items = 10)\nlrt20_df <- readRDS(\"data/lrt20.rds\") %>% \n  bind_rows() %>% \n  select(!i) %>% \n  rename(samplesize = n) %>% \n  add_column(n_items = 20)\nlrt40_df <- readRDS(\"data/lrt40.rds\") %>% \n  bind_rows() %>% \n  select(!i) %>% \n  rename(samplesize = n) %>% \n  add_column(n_items = 40)\n\nlrt_targ <- rbind(lrt0_df,lrt1_df,lrt2_df)\nlrt_n <- rbind(lrt10_df,lrt20_df,lrt40_df)\n```\n:::\n\n::: {#fig-lrt1 .cell layout-ncol=\"1\"}\n\n```{.r .cell-code .hidden}\nlrt_targ %>% \n  mutate(p_corr = ifelse(p < .05, \"correct\",\"false\")) %>% \n  group_by(samplesize,targeting) %>% \n  dplyr::count(p_corr) %>% \n  mutate(Percent = n*100/sum(n) %>% round(1)) %>% \n  ungroup() %>% \n  filter(p_corr == \"correct\") %>% \n  mutate(Targeting = factor(targeting, levels = c(0,1,2), labels = c('On target','1 logit offset','2 logits offset')),\n         samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\",\n                                  \"n = 2000\"))) %>% \n  \n  ggplot(aes(x = samplesize, y = Percent, fill = Targeting)) +\n  geom_col(position = \"dodge\") +\n  geom_text(aes(label = paste0(Percent,\"%\")), \n            color = \"black\",\n            position = position_dodge(width = 0.9),\n            hjust = 1.2, vjust = 0.5,\n            angle = 90\n            ) +\n  theme_rise(fontfamily = \"sans\") +\n  scale_fill_brewer(palette = \"Greens\") +\n  labs(y = \"Detection rate in percent\",\n       #title = \"Detection rate for LRT across sample sizes and location of misfit item\",\n       subtitle = \"One item out of 20 with misfit. 1000 simulations.\",\n       x = \"Sample size\")\n\n\nlrt_n %>% \n  mutate(p_corr = ifelse(p < .05, \"correct\",\"false\")) %>% \n  group_by(samplesize,n_items) %>% \n  dplyr::count(p_corr) %>% \n  mutate(Percent = n*100/sum(n) %>% round(1)) %>% \n  ungroup() %>% \n  filter(p_corr == \"correct\") %>% \n  mutate(n_items = factor(n_items, levels = c(10,20,40), labels = c('10 items (1 misfit)','20 items (3 misfit)','40 items (3 misfit)')),\n         samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\",\n                                  \"n = 2000\"))) %>% \n  \n  ggplot(aes(x = samplesize, y = Percent, fill = n_items)) +\n  geom_col(position = \"dodge\") +\n  geom_text(aes(label = paste0(Percent,\"%\")), \n            color = \"black\",\n            position = position_dodge(width = 0.9),\n            hjust = 1.2, vjust = 0.5,\n            angle = 90\n            ) +\n  theme_rise(fontfamily = \"sans\") +\n  scale_fill_brewer('Number of items') +\n  labs(y = \"Detection rate in percent\",\n       #title = \"Detection rate for LRT across sample sizes and number of items\",\n       subtitle = \"1000 simulations.\",\n       x = \"Sample size\")\n```\n\n::: {.cell-output-display}\n![Across sample sizes and location of misfit item](index_files/figure-pdf/fig-lrt1-1.pdf){#fig-lrt1-1}\n:::\n\n::: {.cell-output-display}\n![Across sample sizes and number of items](index_files/figure-pdf/fig-lrt1-2.pdf){#fig-lrt1-2}\n:::\n\nLikelihood ratio test detection rate\n:::\n\n\n\n\n\nResults for targeting of the misfit item are summarized in @fig-lrt1, where the detection rate is reported based on the proportion of p-values below .05 in each condition.\n\nLRT performs better than item-restscore for the off-target item conditions, especially when targeting was at -2 logits. Otherwise, performance is similar. Infit is better than LRT for n < 500 when targeting = 0, similar at targeting = 1, and LRT is better than infit at targeting -2.\n\nLooking at LRT for different numbers of items and comparing to results for infit and item-restscore at their best detection rates for the corresponding number of items and sample size, it shows much worse performance for 10 items compared to infit and item-restscore at n = 150, but similar performance at larger sample sizes. For 20 and 40 items, LRT is similar to infit at all sample sizes, and slightly better than item-restscore for n < 500.\n\nIt should be noted that LRT also is sensitive to larger sample sizes and increased numbers of items, see <https://pgmj.github.io/clrt.html> for a brief example, and is likely to have a higher error rate than the nominal 5% under many conditions.\n\n# Discussion\n\nThis paper was created primarily out of a desire to understand the performance of conditional item fit and item-restscore in detecting item misfit. Studies 1-3 and 5 were originally planned, while study 4 was added due to the results of previous studies showing issues with large sample sizes, and study 6 was added mostly for didactic purposes but also out of curiosity of the global fit LRT performance compared to the other methods. Müller's [-@muller_item_2020] paper on conditional item fit was published five years ago with results that should have sparked discussions in the Rasch community about updating methods (and software) and the justification of rule-of-thumb critical values. We hope that this paper can help spur such discussions by the simple methodology and presentation of results used, which could make this paper more accessible for practitioners.\n\nMain results summarized: \n\n- small samples (n < 250-500) with small numbers of items make it harder to detect misfitting items\n- small samples (n < 250-500) should rely primarily on conditional item infit with simulation-based critical values\n- large samples (n > 500) should use bootstrapped item-restscore to reduce the risk of falsely identifying misfit\n- misfit in an off-target item is harder to detect than well-targeted items and the LRT test can assist in identifying misfit in off-target items\n- increased number of items increases the power to detect misfit\n\nAssessment of item fit and dimensionality should always be done using multiple methods. Study 6 showed the benefits of also looking at the likelihood ratio test when the misfitting item is located -2 logits away from the sample mean location. Previous simulation studies concluded that the LRT did not perform well at detecting multidimensionality, which is how the misfitting items were generated in this study. While no method in this study achieved very good results at the lowest sample size (n = 150), LRT did not do much worse than the other methods.\n\n\n\n\n\n::: {#cell-fig-loadloc .cell}\n\n```{.r .cell-code .hidden}\nRIloadLoc(simdata3[1:400,], model = \"RM\")\n```\n\n::: {.cell-output-display}\n![Standardized loadings on first residual contrast factor and item location](index_files/figure-pdf/fig-loadloc-1.pdf){#fig-loadloc fig-pos='H'}\n:::\n:::\n\n\n\n\n\nItem fit and item-restscore are recommended to be used in parallel, while also examining residual patterns by reviewing standardized factor loadings on the first residual contrast as well as Yen's Q3 residual correlations [@christensen_critical_2017]. @fig-loadloc illustrates an example, using n = 400 and 3/20 items misfitting, where it is clearly seen how the misfitting items form a separate cluster on the x axis. Regarding residual correlations and critical values, the `easyRasch` package also contains a function to use bootstrapping (`RIgetResidCor()`), similar to the `RIgetfit()` function, to determine the appropriate cutoff. This is described briefly in a blog post [@johansson_simulation_2024] and a simulation paper is under preparation.\n\nThe findings reported here also make a good argument for removing one item at a time when the analysis indicates several misfitting items, starting with the most underfitting item. Such practice would reduce the risk for type-1 errors. This is especially relevant for n >= 500 and when truly misfitting items are located close to the sample mean, when the risk for false positive misfit indication is elevated. In a situation where the analysis of residual patterns using PCA and Yen's Q3 clearly shows clustering of items, it can be justified to remove several items simultaneously.\n\nItem fit in this paper has been assessed using data from individual respondent residuals in a sample. A useful additional method to analyze and understand item fit and misfit is to inspect item characteristic curves where the sample is divided into class intervals based on their total score and the group residuals are inspected [@buchardt_visualizing_2023].\n\nWhile the simulations in this paper have all used dichotomous data, all functions evaluated from the `easyRasch` package also work with polytomous data using the Rasch Partial Credit Model [PCM, @masters_rasch_1982].\n\n## Limitations\n\nWhen doing simulation studies there is always a balance to strike between trying to evaluate many scenarios and not having too high complexity. We have been keeping several things constant, such as item locations and number of items, which makes interpretation easier but may limit the applicability of the results.\n\nThe total number of items and the proportion of misfit items clearly have effects on detection rate and could have been investigated further using more variations in sample sizes. The Rasch partial credit model for polytomous data would have been useful to include in a comparison study. When testing the bootstrapped item-restscore method, more variations in the number of bootstrap samples (iterations) might have been of interest, although the difference between 250 and 500 was small.\n\n# Conclusion\n\nFor sample sizes under 500, it seems best to rely mostly on item infit with simulation-based critical values, using 100 iterations with `RIgetfit()`. For sample sizes closer to 500, item-restscore is recommended as the primary method, either as a single-run test or bootstrapped. With samples larger than 500, bootstrapped item-restscore controls false positive rates well, while showing high rates of misfit detection. Using 250 iterations for the bootstrapped item-restscore seems adequate. In general, both infit and item-restscore are useful in the analysis process if you have a sample size below 1000.\n\n\n\n# References {.unnumbered}\n\n:::{#refs}\n\n:::\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n# Additional materials {#sec-addmat}\n\n- GitHub link for `easyRasch` source code: <https://github.com/pgmj/easyRasch/>\n  - Most functions are defined in this file: <https://github.com/pgmj/easyRasch/blob/main/R/easyRasch.R>\n  \n\n## Results tables\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# library(gt)\n# \n# # APA table styling from <https://gist.github.com/pdparker/1b61b6d36d09cb295bf286a931990159>\n# apa_style <- function(data) {\n#   data %>%\n#     opt_table_lines(extent = \"none\") %>%\n#     tab_options(\n#       heading.border.bottom.width = 2,\n#       heading.border.bottom.color = \"black\",\n#       heading.border.bottom.style = \"solid\",\n#       table.border.top.color = \"white\",\n#       table_body.hlines.color = \"white\",\n#       table_body.border.top.color = \"black\",\n#       table_body.border.top.style = \"solid\",\n#       table_body.border.top.width = 1,\n#       heading.title.font.size = 12,\n#       table.font.size = 12,\n#       heading.subtitle.font.size = 12,\n#       table_body.border.bottom.color = \"black\",\n#       table_body.border.bottom.width = 1,\n#       table_body.border.bottom.style = \"solid\",\n#       column_labels.border.bottom.color = \"black\",\n#       column_labels.border.bottom.style = \"solid\",\n#       column_labels.border.bottom.width = 1\n#     ) %>%\n#       opt_table_font(font = \"times\")\n# }\n# library(flextable)\n# set_flextable_defaults(digits = 1)\noptions(knitr.kable.NA = \"0\")\n```\n:::\n\n\n\n\n\n### Study 1: Item infit and outfit {#sec-tblinfitresults}\n\n#### 100 iterations\n\n\n\n\n\n::: {#tbl-ifbresults1000 .cell tbl-cap='Conditional infit detection rate, 100 bootstrap iterations, targeting = 0 logit'}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 0\n         ) %>% \n  count(item, .drop = F) %>% \n  mutate(`Percent misfit` = n/500*100) %>% \n  ungroup() %>% \n  mutate(`Bootstrap iterations` = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         `Sample size` = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         Item = factor(item, levels = 1:20, ordered = T),\n         Targeting = factor(targeting, levels = c(0,1,2), labels = c('Misfit item 0 logit offset','Misfit item -1 logit offset','Misfit item -2 logits offset'))\n         ) %>% \n  mutate(Targeting = gsub(\"<\",\"=\",Targeting)) %>% \n  select(`Sample size`,`Bootstrap iterations`,Item,`Percent misfit`) %>% \n  filter(`Bootstrap iterations` == \"100 iterations\") %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:20, ordered = T)) %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|--------:|\n|1    |     1.0|     1.2|     1.6|      1.4|\n|2    |     2.0|     1.0|     3.8|      2.0|\n|3    |     0.8|     1.2|     2.2|      4.4|\n|4    |     0.8|     1.4|     2.6|      6.0|\n|5    |     1.4|     0.8|     0.2|      1.0|\n|6    |     1.4|     2.0|     2.2|      2.4|\n|7    |     2.2|     3.4|     8.2|     16.0|\n|8    |     1.0|     0.8|     1.2|      3.6|\n|9    |    80.0|    96.6|   100.0|    100.0|\n|10   |     0.6|     0.4|     1.8|      0.6|\n|11   |     1.8|     2.2|     0.8|      1.6|\n|12   |     1.4|     1.8|     2.2|      5.6|\n|13   |     1.2|     1.4|     1.8|      0.8|\n|14   |     1.8|     2.0|     1.2|      2.0|\n|15   |     1.6|     1.0|     2.0|      2.2|\n|16   |     1.2|     1.8|     2.2|      2.0|\n|17   |     1.2|     1.6|     2.0|      4.0|\n|18   |     2.2|     3.4|     5.0|      4.2|\n|19   |     1.4|     1.4|     2.2|      5.6|\n|20   |     1.6|     1.8|     2.0|      2.8|\n\n\n:::\n:::\n\n::: {#tbl-ifbresults1001 .cell tbl-cap='Conditional infit detection rate, 100 bootstrap iterations, targeting = -1 logit'}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 1\n         ) %>% \n  count(item, .drop = F) %>% \n  mutate(`Percent misfit` = n/500*100) %>% \n  ungroup() %>% \n  mutate(`Bootstrap iterations` = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         `Sample size` = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         Item = factor(item, levels = 1:20, ordered = T),\n         Targeting = factor(targeting, levels = c(0,1,2), labels = c('Misfit item 0 logit offset','Misfit item -1 logit offset','Misfit item -2 logits offset'))\n         ) %>% \n  mutate(Targeting = gsub(\"<\",\"=\",Targeting)) %>% \n  select(`Sample size`,`Bootstrap iterations`,Item,`Percent misfit`) %>% \n  filter(`Bootstrap iterations` == \"100 iterations\") %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:20, ordered = T)) %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|--------:|\n|1    |     0.8|     1.6|     2.8|      1.0|\n|2    |     0.6|     2.0|     1.8|      2.6|\n|3    |     1.8|     2.6|     1.4|      3.6|\n|4    |     1.2|     1.2|     1.0|      0.8|\n|5    |     1.2|     1.0|     1.0|      1.2|\n|6    |     0.2|     1.4|     0.6|      1.6|\n|7    |     1.6|     2.6|     1.4|      2.2|\n|8    |     0.6|       0|     1.2|      1.4|\n|9    |     1.2|     2.2|     0.8|      3.2|\n|10   |     2.0|     1.8|     0.8|      1.6|\n|11   |     1.2|     1.6|     3.0|      4.8|\n|12   |     1.4|     2.4|     3.6|      5.8|\n|13   |     1.6|     1.4|     3.2|      2.2|\n|14   |     1.4|     2.2|     2.2|      2.4|\n|15   |     1.4|     1.4|     1.6|      3.0|\n|16   |     0.6|     1.0|     1.6|      1.2|\n|17   |     1.0|     1.0|     2.6|      3.0|\n|18   |    78.2|    96.2|   100.0|    100.0|\n|19   |     1.2|     1.8|     1.2|      2.0|\n|20   |     2.6|     3.8|     2.2|      4.6|\n\n\n:::\n:::\n\n::: {#tbl-ifbresults1002 .cell tbl-cap='Conditional infit detection rate, 100 bootstrap iterations, targeting = -2 logits'}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 2\n         ) %>% \n  count(item, .drop = F) %>% \n  mutate(`Percent misfit` = n/500*100) %>% \n  ungroup() %>% \n  mutate(`Bootstrap iterations` = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         `Sample size` = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         Item = factor(item, levels = 1:20, ordered = T),\n         Targeting = factor(targeting, levels = c(0,1,2), labels = c('Misfit item 0 logit offset','Misfit item -1 logit offset','Misfit item -2 logits offset'))\n         ) %>% \n  mutate(Targeting = gsub(\"<\",\"=\",Targeting)) %>% \n  select(`Sample size`,`Bootstrap iterations`,Item,`Percent misfit`) %>% \n  filter(`Bootstrap iterations` == \"100 iterations\") %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:20, ordered = T)) %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|--------:|\n|1    |     1.2|     1.0|     1.4|      1.6|\n|2    |     2.2|     2.2|     2.4|      2.4|\n|3    |     1.0|     1.0|     1.4|      1.6|\n|4    |     1.6|     1.2|     1.2|      0.6|\n|5    |     0.8|     0.8|     2.0|      1.6|\n|6    |     0.8|     1.4|     1.0|      1.0|\n|7    |     1.8|     1.8|     2.6|      3.2|\n|8    |     0.6|     1.0|     1.8|      0.4|\n|9    |     1.4|     0.6|     1.0|      1.0|\n|10   |     1.2|     1.4|     1.4|      2.0|\n|11   |     1.4|     1.2|     2.2|      2.0|\n|12   |     2.4|     1.2|     3.6|      3.8|\n|13   |    44.6|    70.6|    96.4|    100.0|\n|14   |     1.2|     3.2|     0.8|      2.4|\n|15   |     1.2|     1.2|     1.0|      1.2|\n|16   |     1.6|     0.4|     1.4|      1.0|\n|17   |     2.2|     1.6|     0.2|      0.8|\n|18   |     0.8|     1.0|     2.8|      3.0|\n|19   |     1.4|     1.6|     1.2|      1.6|\n|20   |     0.8|     2.0|     1.8|      1.6|\n\n\n:::\n:::\n\n\n\n\n\n#### 200 iterations\n\n\n\n\n\n::: {#tbl-ifbresults2000 .cell tbl-cap='Conditional infit detection rate, 200 bootstrap iterations, targeting = 0 logit'}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 0\n         ) %>% \n  count(item, .drop = F) %>% \n  mutate(`Percent misfit` = n/500*100) %>% \n  ungroup() %>% \n  mutate(`Bootstrap iterations` = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         `Sample size` = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         Item = factor(item, levels = 1:20, ordered = T),\n         Targeting = factor(targeting, levels = c(0,1,2), labels = c('Misfit item 0 logit offset','Misfit item -1 logit offset','Misfit item -2 logits offset'))\n         ) %>% \n  mutate(Targeting = gsub(\"<\",\"=\",Targeting),\n         `Percent misfit` = car::recode(`Percent misfit`,\"NA=0\")) %>% \n  \n  select(`Sample size`,`Bootstrap iterations`,Item,`Percent misfit`) %>% \n  filter(`Bootstrap iterations` == \"200 iterations\") %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:20, ordered = T)) %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|--------:|\n|1    |       0|     0.4|     0.2|      0.2|\n|2    |     0.8|     0.8|     1.8|      1.0|\n|3    |     0.4|     0.2|     1.0|      1.6|\n|4    |     0.6|     0.6|     1.2|      4.0|\n|5    |     0.8|     0.4|     0.4|      1.0|\n|6    |     0.6|     1.0|     0.8|      1.6|\n|7    |     0.8|     2.0|     4.6|     11.2|\n|8    |     0.6|     1.0|       0|      1.6|\n|9    |    76.8|    94.6|   100.0|    100.0|\n|10   |     0.4|     0.4|     1.4|      0.2|\n|11   |     0.6|     1.4|     0.6|      0.6|\n|12   |     1.2|     0.8|     0.8|      2.6|\n|13   |     0.8|     0.4|     0.8|      0.6|\n|14   |     0.4|     0.4|     1.2|      0.4|\n|15   |     0.8|       0|     0.6|      1.6|\n|16   |     0.8|     0.6|     1.0|      0.8|\n|17   |     1.0|     0.8|     1.2|      1.4|\n|18   |     1.0|     0.8|     2.0|      2.2|\n|19   |     0.2|     0.2|     2.0|      2.2|\n|20   |     1.0|     1.0|     1.0|      1.2|\n\n\n:::\n\n```{.r .cell-code .hidden}\n  # #group_by(Targeting) %>% \n  # as_grouped_data(\"Targeting\") %>% \n  # #arrange(Item) %>% \n  # flextable() %>%\n  # autofit() %>% \n  # theme_apa() %>% \n  # colformat_double()\n```\n:::\n\n::: {#tbl-ifbresults2001 .cell tbl-cap='Conditional infit detection rate, 200 bootstrap iterations, targeting = -1 logit'}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 1\n         ) %>% \n  count(item, .drop = F) %>% \n  mutate(`Percent misfit` = n/500*100) %>% \n  ungroup() %>% \n  mutate(`Bootstrap iterations` = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         `Sample size` = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         Item = factor(item, levels = 1:20, ordered = T),\n         Targeting = factor(targeting, levels = c(0,1,2), labels = c('Misfit item 0 logit offset','Misfit item -1 logit offset','Misfit item -2 logits offset'))\n         ) %>% \n  mutate(Targeting = gsub(\"<\",\"=\",Targeting),\n         `Percent misfit` = car::recode(`Percent misfit`,\"NA=0\")) %>% \n  \n  select(`Sample size`,`Bootstrap iterations`,Item,`Percent misfit`) %>% \n  filter(`Bootstrap iterations` == \"200 iterations\") %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:20, ordered = T)) %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|--------:|\n|1    |     0.6|       0|     0.8|      1.2|\n|2    |     1.0|     0.6|     0.4|      2.2|\n|3    |     0.4|     0.2|     0.8|      1.8|\n|4    |     0.8|     0.6|     0.6|      0.2|\n|5    |     0.4|     0.4|     0.4|      0.2|\n|6    |     1.2|     0.6|     0.4|      0.8|\n|7    |     0.8|     1.2|     0.4|      0.8|\n|8    |     0.2|       0|     0.4|      0.8|\n|9    |     0.4|     1.4|     0.2|      1.6|\n|10   |     1.0|     1.4|     1.0|      0.4|\n|11   |     1.0|     1.4|     2.2|      3.2|\n|12   |     0.6|     1.4|     2.2|      2.8|\n|13   |     1.2|     0.4|     1.8|      1.8|\n|14   |     0.6|     1.2|     1.8|      1.2|\n|15   |     1.6|     1.2|     0.6|      2.0|\n|16   |     0.4|     0.2|     0.8|      0.4|\n|17   |     0.6|     0.2|     1.2|      1.0|\n|18   |    74.6|    93.4|   100.0|    100.0|\n|19   |     0.8|     1.0|     0.8|      0.8|\n|20   |     1.8|     2.0|     1.6|      3.4|\n\n\n:::\n\n```{.r .cell-code .hidden}\n  # #group_by(Targeting) %>% \n  # as_grouped_data(\"Targeting\") %>% \n  # #arrange(Item) %>% \n  # flextable() %>%\n  # autofit() %>% \n  # theme_apa() %>% \n  # colformat_double()\n```\n:::\n\n::: {#tbl-ifbresults2002 .cell tbl-cap='Conditional infit detection rate, 200 bootstrap iterations, targeting = -2 logits'}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 2\n         ) %>% \n  count(item, .drop = F) %>% \n  mutate(`Percent misfit` = n/500*100) %>% \n  ungroup() %>% \n  mutate(`Bootstrap iterations` = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         `Sample size` = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         Item = factor(item, levels = 1:20, ordered = T),\n         Targeting = factor(targeting, levels = c(0,1,2), labels = c('Misfit item 0 logit offset','Misfit item -1 logit offset','Misfit item -2 logits offset'))\n         ) %>% \n  mutate(Targeting = gsub(\"<\",\"=\",Targeting),\n         `Percent misfit` = car::recode(`Percent misfit`,\"NA=0\")) %>% \n  \n  select(`Sample size`,`Bootstrap iterations`,Item,`Percent misfit`) %>% \n  filter(`Bootstrap iterations` == \"200 iterations\") %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:20, ordered = T)) %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|--------:|\n|1    |     0.4|     0.8|     0.6|      0.8|\n|2    |     0.4|     1.4|     1.2|      1.6|\n|3    |     0.6|     1.2|     0.6|      0.8|\n|4    |     0.4|     0.8|     0.6|      0.2|\n|5    |     0.2|       0|     1.0|      1.0|\n|6    |     1.0|     0.8|     0.6|      0.6|\n|7    |     1.0|     0.8|     1.2|      1.4|\n|8    |     0.4|     0.6|     0.8|      0.2|\n|9    |     1.4|     0.2|     0.4|      0.8|\n|10   |     0.6|     0.6|     0.8|      0.6|\n|11   |     0.4|     0.8|     1.0|      1.0|\n|12   |     0.8|     0.8|     2.0|      2.0|\n|13   |    37.2|    63.0|    95.0|    100.0|\n|14   |     0.4|     2.0|     0.4|      0.4|\n|15   |     0.4|     0.4|     0.6|      0.6|\n|16   |     0.8|       0|     1.0|      0.6|\n|17   |     0.8|     0.6|     0.6|      0.2|\n|18   |     0.4|     1.0|     2.2|      2.0|\n|19   |     0.6|     0.8|     0.6|      0.4|\n|20   |     0.6|     1.0|     1.0|      1.0|\n\n\n:::\n\n```{.r .cell-code .hidden}\n  # #group_by(Targeting) %>% \n  # as_grouped_data(\"Targeting\") %>% \n  # #arrange(Item) %>% \n  # flextable() %>%\n  # autofit() %>% \n  # theme_apa() %>% \n  # colformat_double()\n```\n:::\n\n\n\n\n\n#### 400 iterations\n\n\n\n\n\n::: {#tbl-ifbresults4000 .cell tbl-cap='Conditional infit detection rate, 400 bootstrap iterations, targeting = 0 logit'}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 0\n         ) %>% \n  count(item, .drop = F) %>% \n  mutate(`Percent misfit` = n/500*100) %>% \n  ungroup() %>% \n  mutate(`Bootstrap iterations` = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         `Sample size` = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         Item = factor(item, levels = 1:20, ordered = T),\n         Targeting = car::recode(targeting,\"0='Misfit item 0 logit offset';1='Misfit item -1 logit offset';2='Misfit item -2 logits offset'\", as.factor = TRUE)\n         ) %>% \n  #mutate(Targeting = gsub(\"<\",\"=\",Targeting)) %>% \n  select(`Sample size`,`Bootstrap iterations`,Item,`Percent misfit`) %>% \n  filter(`Bootstrap iterations` == \"400 iterations\") %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:20, ordered = T)) %>% \n  #group_by(Targeting) %>% \n  #as_grouped_data(\"Targeting\") %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|--------:|\n|1    |     0.4|     0.2|       0|        0|\n|2    |     0.2|     0.6|     0.8|      0.8|\n|3    |     0.4|     0.2|     0.4|      2.0|\n|4    |     0.2|     0.4|     0.2|      2.0|\n|5    |     0.6|     0.2|     0.6|      0.6|\n|6    |     0.2|     0.6|     0.4|      0.6|\n|7    |     0.6|     0.8|     2.6|      7.8|\n|8    |     0.4|     0.2|     0.2|      1.2|\n|9    |    69.4|    92.0|   100.0|    100.0|\n|10   |       0|     0.4|     0.2|      0.4|\n|11   |     0.4|     0.6|       0|      0.6|\n|12   |     0.4|     0.6|     0.6|      1.2|\n|13   |     0.2|     0.2|     0.8|        0|\n|14   |     0.2|       0|     0.2|      0.8|\n|15   |     0.4|     0.2|     0.2|        0|\n|16   |     0.8|     0.2|     0.4|      0.4|\n|17   |       0|     0.4|     0.4|      1.2|\n|18   |     0.6|     1.2|     1.2|      0.8|\n|19   |       0|       0|     0.6|      1.6|\n|20   |     0.6|     0.4|     0.6|      1.2|\n\n\n:::\n\n```{.r .cell-code .hidden}\n  # flextable() %>%\n  # autofit() %>% \n  # theme_apa() %>% \n  # colformat_double() \n```\n:::\n\n::: {#tbl-ifbresults4001 .cell tbl-cap='Conditional infit detection rate, 400 bootstrap iterations, targeting = -1 logit'}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 1\n         ) %>% \n  count(item, .drop = F) %>% \n  mutate(`Percent misfit` = n/500*100) %>% \n  ungroup() %>% \n  mutate(`Bootstrap iterations` = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         `Sample size` = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         Item = factor(item, levels = 1:20, ordered = T),\n         Targeting = car::recode(targeting,\"0='Misfit item 0 logit offset';1='Misfit item -1 logit offset';2='Misfit item -2 logits offset'\", as.factor = TRUE)\n         ) %>% \n  #mutate(Targeting = gsub(\"<\",\"=\",Targeting)) %>% \n  select(`Sample size`,`Bootstrap iterations`,Item,`Percent misfit`) %>% \n  filter(`Bootstrap iterations` == \"400 iterations\") %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:20, ordered = T)) %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|--------:|\n|1    |       0|       0|       0|      0.4|\n|2    |       0|     0.4|     0.6|      0.6|\n|3    |     0.4|     0.6|     0.4|      0.6|\n|4    |       0|     0.2|     0.4|        0|\n|5    |     0.4|     0.4|     0.6|        0|\n|6    |       0|       0|     0.2|      0.2|\n|7    |     0.4|     0.4|     0.2|      0.6|\n|8    |     0.2|       0|     0.4|      0.8|\n|9    |       0|       0|     0.4|      1.2|\n|10   |     0.8|     0.8|     0.6|      0.2|\n|11   |     0.4|     1.0|     1.8|      1.0|\n|12   |     0.2|     0.6|     1.2|      1.0|\n|13   |     0.6|       0|     1.0|      0.8|\n|14   |     0.4|     0.4|     1.2|      1.0|\n|15   |     0.4|     0.4|     0.4|      0.6|\n|16   |     0.4|     0.4|     0.4|      0.2|\n|17   |       0|     0.8|     0.4|      0.6|\n|18   |    68.6|    94.2|   100.0|    100.0|\n|19   |     0.4|     1.0|     0.2|      0.8|\n|20   |     1.2|     1.0|     0.8|      1.4|\n\n\n:::\n:::\n\n::: {#tbl-ifbresults4002 .cell tbl-cap='Conditional infit detection rate, 400 bootstrap iterations, targeting = -2 logits'}\n\n```{.r .cell-code .hidden}\nifb %>% \n  group_by(targeting, samplesize, sims) %>% \n  filter(!infit_diff == \"no misfit\",\n         targeting == 2\n         ) %>% \n  count(item, .drop = F) %>% \n  mutate(`Percent misfit` = n/500*100) %>% \n  ungroup() %>% \n  mutate(`Bootstrap iterations` = factor(sims, levels = c(100,200,400),\n                       labels = c(\"100 iterations\",\n                                  \"200 iterations\",\n                                  \"400 iterations\")),\n         `Sample size` = factor(samplesize, levels = c(150,250,500,1000),\n                       labels = c(\"n = 150\",\n                                  \"n = 250\",\n                                  \"n = 500\",\n                                  \"n = 1000\")),\n         Item = factor(item, levels = 1:20, ordered = T),\n         Targeting = car::recode(targeting,\"0='Misfit item 0 logit offset';1='Misfit item -1 logit offset';2='Misfit item -2 logits offset'\", as.factor = TRUE)\n         ) %>% \n  #mutate(Targeting = gsub(\"<\",\"=\",Targeting)) %>% \n  select(`Sample size`,`Bootstrap iterations`,Item,`Percent misfit`) %>% \n  filter(`Bootstrap iterations` == \"400 iterations\") %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:20, ordered = T)) %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|--------:|\n|1    |     0.2|       0|     0.2|      0.4|\n|2    |     0.4|     0.6|     1.2|      0.4|\n|3    |     0.2|     0.4|     0.4|      0.6|\n|4    |     0.4|     0.4|     0.2|      0.2|\n|5    |     0.2|       0|     0.6|      0.2|\n|6    |     0.2|     0.8|       0|      0.2|\n|7    |     0.6|     0.6|     0.4|      0.6|\n|8    |     0.2|     0.2|     0.2|        0|\n|9    |     0.2|       0|     0.4|      0.2|\n|10   |     0.2|       0|       0|      0.4|\n|11   |     0.4|     0.2|     0.6|      0.4|\n|12   |     0.8|       0|     0.8|      1.6|\n|13   |    29.8|    55.6|    93.4|    100.0|\n|14   |     0.2|     0.8|       0|      0.4|\n|15   |       0|     0.2|     0.2|      0.6|\n|16   |     0.8|     0.2|     0.6|      0.2|\n|17   |     0.4|       0|     0.4|      0.2|\n|18   |     0.2|     0.4|     1.2|      1.4|\n|19   |     0.4|     0.6|     0.4|      0.2|\n|20   |       0|     0.2|     0.4|      0.6|\n\n\n:::\n:::\n\n\n\n\n\n### Study 2: Item-restscore {#sec-tblirresults}\n\n\n\n\n\n::: {#tbl-irresults0 .cell tbl-cap='Item-restscore detection rate, targeting = 0 logit'}\n\n```{.r .cell-code .hidden}\nir_results %>% \n  group_by(targeting, samplesize) %>% \n  filter(ir_padj == \"sign. misfit\",\n         targeting == 0) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/1000,\n         targeting = factor(targeting, levels = c(0,1,2), labels = c('Misfit item 0 logit offset','Misfit item -1 logit offset','Misfit item -2 logits offset')),\n         item = factor(item),\n         samplesize = car::recode(samplesize,\"100='n < 100';150='n < 150';250='n < 250';500='n < 500';1000='n < 1000'\")) %>% \n  mutate(samplesize = gsub(\"<\",\"=\",samplesize)) %>% \n  rename(Targeting = targeting,\n         `Sample size` = samplesize,\n         Item = item,\n         `Percent misfit` = Percent) %>% \n  select(!n) %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:20, ordered = T)) %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: There were 5 warnings in `mutate()`.\nThe first warning was:\ni In argument: `samplesize = car::recode(samplesize, \"100='n < 100';150='n <\n  150';250='n < 250';500='n < 500';1000='n < 1000'\")`.\ni In group 1: `targeting = 0` and `samplesize = 100`.\nCaused by warning in `car::recode()`:\n! NAs introduced by coercion\ni Run `dplyr::last_dplyr_warnings()` to see the 4 remaining warnings.\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|Item | n = 100| n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|-------:|--------:|\n|1    |     5.5|     2.7|     2.3|     2.6|      3.7|\n|2    |     1.9|     1.6|     1.2|     1.2|      0.7|\n|3    |     0.6|     0.6|     0.3|     0.9|      0.2|\n|4    |     1.8|     1.7|     1.5|     0.8|      0.9|\n|5    |     2.8|     2.1|     1.4|     1.9|      4.4|\n|6    |     2.7|     1.0|     0.8|     0.4|      0.6|\n|7    |     0.7|     0.9|     1.0|     1.0|      2.0|\n|8    |     2.4|     3.5|     2.2|     3.7|      5.4|\n|9    |    44.0|    66.0|    95.2|    99.9|    100.0|\n|10   |     1.3|     0.6|     0.7|     0.4|      0.6|\n|11   |     2.1|     2.4|     2.3|     1.9|      5.5|\n|12   |     2.8|     2.2|     1.9|     1.9|      2.0|\n|13   |     5.6|     4.6|     3.9|     3.3|      3.9|\n|14   |     1.5|     1.8|     0.9|     1.3|      2.2|\n|15   |     0.5|     0.8|     0.6|     0.3|      0.3|\n|16   |     3.7|     3.4|     3.1|     3.2|      3.6|\n|17   |     2.2|     2.0|     1.2|     0.8|      0.1|\n|18   |     1.6|     2.1|     1.8|     2.0|      2.6|\n|19   |     1.7|     0.8|     0.6|     0.6|      0.5|\n|20   |     1.4|     0.7|     1.1|     0.8|      0.8|\n\n\n:::\n:::\n\n::: {#tbl-irresults1 .cell tbl-cap='Item-restscore detection rate, targeting = -1 logit'}\n\n```{.r .cell-code .hidden}\nir_results %>% \n  group_by(targeting, samplesize) %>% \n  filter(ir_padj == \"sign. misfit\",\n         targeting == 1) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/1000,\n         targeting = factor(targeting, levels = c(0,1,2), labels = c('Misfit item 0 logit offset','Misfit item -1 logit offset','Misfit item -2 logits offset')),\n         item = factor(item),\n         samplesize = car::recode(samplesize,\"100='n < 100';150='n < 150';250='n < 250';500='n < 500';1000='n < 1000'\")) %>% \n  mutate(samplesize = gsub(\"<\",\"=\",samplesize)) %>% \n  rename(Targeting = targeting,\n         `Sample size` = samplesize,\n         Item = item,\n         `Percent misfit` = Percent) %>% \n  select(!n) %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:20, ordered = T)) %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: There were 5 warnings in `mutate()`.\nThe first warning was:\ni In argument: `samplesize = car::recode(samplesize, \"100='n < 100';150='n <\n  150';250='n < 250';500='n < 500';1000='n < 1000'\")`.\ni In group 1: `targeting = 1` and `samplesize = 100`.\nCaused by warning in `car::recode()`:\n! NAs introduced by coercion\ni Run `dplyr::last_dplyr_warnings()` to see the 4 remaining warnings.\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|Item | n = 100| n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|-------:|--------:|\n|1    |     3.4|     2.3|     1.8|     1.6|      2.2|\n|2    |     2.4|     2.5|     2.3|     2.1|      4.9|\n|3    |     0.9|     0.8|     0.6|     0.1|      0.2|\n|4    |     1.2|     1.7|     0.8|     0.6|      0.6|\n|5    |     1.6|     1.4|     0.7|     0.7|      0.3|\n|6    |     1.8|     1.0|     1.8|     1.0|      2.0|\n|7    |     1.0|     0.7|     0.1|     0.4|      0.4|\n|8    |     1.7|     1.4|     1.5|     1.9|      1.6|\n|9    |     1.2|     1.4|     1.0|     0.7|      1.1|\n|10   |     0.6|     0.5|     0.4|     0.4|      0.5|\n|11   |     2.3|     1.9|     1.5|     1.5|      4.3|\n|12   |     1.3|     0.8|     0.8|     0.2|      0.1|\n|13   |     2.8|     2.4|     1.6|     1.1|      1.6|\n|14   |     1.8|     1.8|     1.0|     1.8|      3.2|\n|15   |     1.2|     1.0|     0.7|     1.5|      1.0|\n|16   |     3.2|     3.5|     2.1|     2.2|      2.4|\n|17   |     2.9|     1.4|     1.3|     0.9|      0.3|\n|18   |    36.4|    61.0|    90.9|   100.0|    100.0|\n|19   |     1.0|     0.9|     1.1|     1.1|      1.4|\n|20   |     1.5|     1.5|     0.7|     1.3|      0.8|\n\n\n:::\n:::\n\n::: {#tbl-irresults2 .cell tbl-cap='Item-restscore detection rate, targeting = -2 logits'}\n\n```{.r .cell-code .hidden}\nir_results %>% \n  group_by(targeting, samplesize) %>% \n  filter(ir_padj == \"sign. misfit\",\n         targeting == 2) %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/1000,\n         targeting = factor(targeting, levels = c(0,1,2), labels = c('Misfit item 0 logit offset','Misfit item -1 logit offset','Misfit item -2 logits offset')),\n         item = factor(item),\n         samplesize = car::recode(samplesize,\"100='n < 100';150='n < 150';250='n < 250';500='n < 500';1000='n < 1000'\")) %>% \n  mutate(samplesize = gsub(\"<\",\"=\",samplesize)) %>% \n  rename(Targeting = targeting,\n         `Sample size` = samplesize,\n         Item = item,\n         `Percent misfit` = Percent) %>% \n  select(!n) %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:20, ordered = T)) %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: There were 5 warnings in `mutate()`.\nThe first warning was:\ni In argument: `samplesize = car::recode(samplesize, \"100='n < 100';150='n <\n  150';250='n < 250';500='n < 500';1000='n < 1000'\")`.\ni In group 1: `targeting = 2` and `samplesize = 100`.\nCaused by warning in `car::recode()`:\n! NAs introduced by coercion\ni Run `dplyr::last_dplyr_warnings()` to see the 4 remaining warnings.\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|Item | n = 100| n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|-------:|--------:|\n|1    |     2.7|     0.4|     0.7|     0.6|      0.3|\n|2    |     2.0|     1.4|     1.5|     0.8|      1.0|\n|3    |     0.7|     0.2|     0.5|     0.2|      0.2|\n|4    |     2.4|     0.8|     0.2|     0.7|      0.1|\n|5    |     0.6|     0.5|     0.2|     0.2|      0.1|\n|6    |     0.8|     0.7|     0.5|     0.3|      0.2|\n|7    |     0.9|     0.5|     0.7|     1.2|      0.7|\n|8    |     1.8|     0.7|     0.3|     0.7|      0.6|\n|9    |     0.9|     0.4|     0.4|     0.2|      0.7|\n|10   |     1.4|     1.0|     0.5|     0.7|      0.8|\n|11   |     1.3|     0.8|     0.6|     0.6|      0.4|\n|12   |     1.0|     1.2|     0.4|     0.4|      0.6|\n|13   |    21.4|    33.4|    62.4|    97.9|    100.0|\n|14   |     1.2|     1.0|     0.8|     1.0|      0.6|\n|15   |     1.1|     1.0|     1.0|     1.0|      2.7|\n|16   |     2.6|     1.8|     0.9|     0.4|      0.5|\n|17   |     2.8|     0.7|     1.5|     1.0|      0.7|\n|18   |     0.9|     0.7|     0.6|     0.6|      0.6|\n|19   |     0.3|     0.2|     0.5|     0.2|        0|\n|20   |     1.6|     0.9|     1.2|     1.2|      1.0|\n\n\n:::\n:::\n\n\n\n\n\n### Study 3: Comparing infit and item-restscore {#sec-infirresults}\n\n\n\n\n\n::: {#tbl-ifb3out .cell tbl-cap='Conditional outfit detection rate with three misfitting items'}\n\n```{.r .cell-code .hidden}\nifb3_df %>% \n  group_by(samplesize) %>% \n  filter(!outfit_diff == \"no misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\")),\n         item = factor(item)) %>% \n  rename(`Sample size` = samplesize,\n         Item = item,\n         `Percent misfit` = Percent) %>% \n  select(!n) %>% \n  pivot_wider(id_cols = Item, names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  arrange(Item) %>% \n  # gt() %>% \n  # sub_missing(missing_text = \"0\") %>% \n  # tab_footnote(footnote = \"Note. Misfitting items are 9, 13, and 18.\") \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000| n = 2000|\n|:----|-------:|-------:|-------:|--------:|--------:|\n|1    |     2.8|     3.4|     2.8|      5.2|      8.0|\n|2    |    11.6|    20.0|    24.2|     36.8|     58.8|\n|3    |     0.4|     0.4|     0.4|      0.4|        0|\n|4    |     3.2|     4.6|     2.6|      7.4|      9.0|\n|5    |       0|       0|       0|        0|      0.2|\n|6    |     9.4|    12.8|    16.8|     27.8|     58.2|\n|7    |     0.8|     2.2|     1.8|      2.8|      6.4|\n|8    |     1.2|     0.8|     1.2|      0.6|      2.6|\n|9    |     3.4|     6.8|    11.0|     64.4|     99.2|\n|10   |     0.4|     0.4|     0.2|      1.2|      3.0|\n|11   |     4.2|     5.4|     8.8|     18.0|     42.0|\n|12   |     1.8|     1.8|     0.4|      1.0|      1.2|\n|13   |    17.8|    32.2|    60.2|     94.0|    100.0|\n|14   |     1.8|     2.6|     1.6|      4.4|     10.2|\n|15   |       0|       0|     0.2|        0|      0.8|\n|16   |     9.0|     9.8|     7.4|     15.2|     30.6|\n|17   |     2.6|     1.8|     3.2|      4.8|      9.8|\n|18   |    38.6|    63.6|    89.8|     99.8|    100.0|\n|19   |       0|     0.2|       0|        0|        0|\n|20   |     7.8|    16.2|    14.4|     29.4|     63.2|\n\n\n:::\n:::\n\n::: {#tbl-ifb3 .cell tbl-cap='Conditional infit detection rate with three misfitting items'}\n\n```{.r .cell-code .hidden}\nifb3_df %>% \n  group_by(samplesize) %>% \n  filter(!infit_diff == \"no misfit\") %>% \n  dplyr::count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\")),\n         item = factor(item)) %>% \n    rename(`Sample size` = samplesize,\n         Item = item,\n         `Percent misfit` = Percent) %>% \n  select(!n) %>% \n  pivot_wider(id_cols = Item, names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  arrange(Item) %>% \n  # gt() %>% \n  # sub_missing(missing_text = \"0\") %>% \n  # tab_footnote(footnote = \"Note. Misfitting items are 9, 13, and 18.\") %>% \n  # apa_style()\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000| n = 2000|\n|:----|-------:|-------:|-------:|--------:|--------:|\n|1    |     1.4|     2.0|     3.6|      3.8|     10.0|\n|2    |     3.2|     7.6|     8.6|     19.0|     48.4|\n|3    |     2.4|     2.4|     2.0|      6.0|     10.8|\n|4    |     1.0|     1.4|     2.0|      5.6|      8.2|\n|5    |     0.8|     3.0|     3.4|      6.2|     11.6|\n|6    |     3.0|     3.8|     4.0|      8.6|     26.0|\n|7    |     2.0|     2.4|     3.0|      7.8|     17.0|\n|8    |     2.8|     3.6|     5.0|      9.4|     27.4|\n|9    |    59.2|    87.0|    99.6|    100.0|    100.0|\n|10   |     2.4|     4.4|     5.4|      8.4|     22.0|\n|11   |     2.8|     2.0|     3.4|     11.2|     26.0|\n|12   |     1.6|     1.8|     0.8|      1.4|      2.6|\n|13   |    19.0|    32.0|    65.6|     95.4|    100.0|\n|14   |     2.2|     3.0|     1.8|      4.8|      7.4|\n|15   |     1.4|     2.6|     3.6|      8.8|     20.2|\n|16   |     3.0|     2.8|     2.8|      3.6|     13.0|\n|17   |     1.6|     1.2|     1.2|      0.8|      1.2|\n|18   |    51.8|    75.0|    94.8|    100.0|    100.0|\n|19   |     2.2|     1.4|     0.4|      0.2|      0.6|\n|20   |     2.4|     5.2|     4.2|     10.6|     30.6|\n\n\n:::\n:::\n\n::: {#tbl-ifb3b .cell tbl-cap='Conditional infit detection rate with three misfitting items and increased truncation'}\n\n```{.r .cell-code .hidden}\nifb3c_df %>% \n  group_by(samplesize) %>% \n  filter(!infit_diff == \"no misfit\",\n         samplesize < 400) %>% \n  dplyr::count(item, .drop = F) %>% \n  mutate(Percent = n/500*100) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\")),\n         item = factor(item)) %>% \n  rename(`Sample size` = samplesize,\n         Item = item,\n         `Percent misfit` = Percent) %>% \n  select(!n) %>% \n  pivot_wider(id_cols = Item, names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  arrange(Item) %>% \n  # gt() %>% \n  # sub_missing(missing_text = \"0\") %>% \n  # tab_footnote(footnote = \"Note. Misfitting items are 9, 13, and 18.\") %>% \n  # apa_style()\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250|\n|:----|-------:|-------:|\n|1    |     2.0|     1.4|\n|2    |     5.2|     6.4|\n|3    |     3.0|     3.0|\n|4    |     2.4|     2.4|\n|5    |     1.6|     3.8|\n|6    |     3.4|     4.4|\n|7    |     3.6|     5.4|\n|8    |     3.8|     5.4|\n|9    |    66.4|    90.4|\n|10   |     3.0|     4.0|\n|11   |     2.2|     3.2|\n|12   |     3.0|     2.0|\n|13   |    21.2|    42.6|\n|14   |     2.4|     3.0|\n|15   |     1.8|     2.4|\n|16   |     2.8|     3.0|\n|17   |     2.2|     0.6|\n|18   |    53.0|    82.0|\n|19   |     1.8|     1.4|\n|20   |     3.6|     5.8|\n\n\n:::\n:::\n\n::: {#tbl-itemrestscore2 .cell tbl-cap='Item-restscore detection rate with three misfitting items'}\n\n```{.r .cell-code .hidden}\nir3_df %>% \n  group_by(samplesize) %>% \n  filter(ir_padj == \"sign. misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/500) %>% \n  ungroup() %>% \n  mutate(item = factor(item)) %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\"))) %>% \n    rename(`Sample size` = samplesize,\n         Item = item,\n         `Percent misfit` = Percent) %>% \n  select(!n) %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:20, ordered = T)) %>% \n  arrange(Item) %>% \n  # gt() %>% \n  # sub_missing(missing_text = \"0\") %>% \n  # tab_footnote(footnote = \"Note. Misfitting items are 9, 13, and 18.\") %>% \n  # apa_style()\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000| n = 2000|\n|:----|-------:|-------:|-------:|--------:|--------:|\n|1    |     2.8|     5.4|     5.8|     13.6|     32.2|\n|2    |     4.6|     5.0|     8.6|     24.4|     61.4|\n|3    |     2.2|     3.2|     5.0|      9.2|     25.2|\n|4    |     3.0|     4.0|     4.8|      7.2|     17.2|\n|5    |     2.6|     3.4|     4.4|     15.6|     33.6|\n|6    |     3.0|     5.8|     9.6|     21.4|     55.2|\n|7    |     2.6|     3.6|     5.8|     14.6|     36.0|\n|8    |     3.4|     5.2|     9.8|     14.4|     43.6|\n|9    |    49.2|    77.8|    99.4|    100.0|    100.0|\n|10   |     3.0|     3.8|     7.4|     15.6|     43.2|\n|11   |     2.0|     3.4|     6.4|     14.2|     39.2|\n|12   |     2.2|     3.0|     3.6|      5.2|     16.2|\n|13   |    14.6|    35.0|    70.6|     98.8|    100.0|\n|14   |     1.4|     2.4|     2.2|      8.4|     22.0|\n|15   |     3.2|     2.2|     4.8|     14.6|     37.8|\n|16   |     3.0|     4.6|     8.2|      9.4|     30.4|\n|17   |     3.0|     1.4|     2.8|      6.4|     12.2|\n|18   |    34.6|    62.2|    98.0|    100.0|    100.0|\n|19   |     0.4|     1.0|     2.0|      1.8|      1.0|\n|20   |     3.8|     3.4|     7.4|     18.8|     44.0|\n\n\n:::\n:::\n\n::: {#tbl-comp1 .cell tbl-cap='Detection rate for item-restscore compared to infit'}\n\n```{.r .cell-code .hidden}\nrbind(ifb3_sum,ir3_sum) %>% \n  mutate(item = factor(item, levels = c(9,18,13), labels = c(\"Item 9 (location 0)\",\n                                                             \" Item 18 (location -1)\",\n                                                             \" Item 13 (location -2)\"),\n                       ordered = T)) %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\"))) %>% \n  rename(`Sample size` = samplesize,\n         Item = item,\n         `Percent misfit` = percent) %>% \n  pivot_wider(id_cols = c(Method,Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  arrange(Item) %>% \n  # gt() %>% \n  # sub_missing(missing_text = \"\") %>% \n  # apa_style()\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Method         |Item                  | n = 150| n = 250| n = 500| n = 1000| n = 2000|\n|:--------------|:---------------------|-------:|-------:|-------:|--------:|--------:|\n|Infit          |Item 9 (location 0)   |    59.2|    87.0|    99.6|    100.0|      100|\n|Item-restscore |Item 9 (location 0)   |    49.2|    77.8|    99.4|    100.0|      100|\n|Infit          |Item 18 (location -1) |    51.8|    75.0|    94.8|    100.0|      100|\n|Item-restscore |Item 18 (location -1) |    34.6|    62.2|    98.0|    100.0|      100|\n|Infit          |Item 13 (location -2) |    19.0|    32.0|    65.6|     95.4|      100|\n|Item-restscore |Item 13 (location -2) |    14.6|    35.0|    70.6|     98.8|      100|\n\n\n:::\n:::\n\n\n\n\n\n### Study 5: Varying the number of items \n\n\n\n\n\n::: {#tbl-ifb40 .cell tbl-cap='Conditional infit detection rate with 40 items (3 misfit)'}\n\n```{.r .cell-code .hidden}\nifb40_df %>% \n  group_by(samplesize) %>% \n  filter(!infit_diff == \"no misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = round(n/200*100,1)) %>% \n  ungroup() %>% \n  mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\"))) %>% \n  rename(`Sample size` = samplesize,\n         Item = item,\n         `Percent misfit` = Percent) %>% \n  select(!n) %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:40, ordered = T)) %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|--------:|\n|1    |     2.5|     2.5|     4.5|      7.0|\n|2    |     2.5|     2.5|     4.0|      2.0|\n|3    |     1.0|     1.0|     3.0|      3.5|\n|4    |     2.0|     3.0|     3.0|      7.0|\n|5    |     1.5|     2.5|     2.5|      1.0|\n|6    |     1.5|       0|     1.5|      2.5|\n|7    |     1.0|     5.5|     6.0|     11.0|\n|8    |     1.0|     3.5|     2.0|      7.5|\n|9    |    87.5|    98.0|   100.0|    100.0|\n|10   |     3.5|     3.0|     4.0|      5.0|\n|11   |     1.5|     3.5|     3.5|      7.0|\n|12   |     2.0|     2.5|     2.5|      2.5|\n|13   |    38.5|    69.5|    95.5|    100.0|\n|14   |     1.5|     2.5|     1.0|      0.5|\n|15   |     3.5|     2.5|     5.0|     11.5|\n|16   |     2.5|     3.0|     1.5|      3.0|\n|17   |     3.0|     4.0|     5.5|      3.5|\n|18   |    74.5|    95.0|   100.0|    100.0|\n|19   |     0.5|     2.5|     2.0|      3.0|\n|20   |     0.5|     1.5|     2.5|      3.5|\n|21   |     2.0|     2.0|     3.0|     10.5|\n|22   |     2.0|     2.5|     1.0|      1.0|\n|23   |     3.5|     3.0|     3.5|      6.5|\n|24   |     1.0|     4.0|     4.0|      1.5|\n|25   |     1.0|     0.5|     2.0|      2.5|\n|26   |     4.5|     5.0|     4.0|      6.5|\n|27   |     2.0|     3.0|     1.5|      6.0|\n|28   |     1.5|     2.5|     2.0|      2.0|\n|29   |     2.5|     2.0|     1.5|      8.0|\n|30   |     0.5|     1.5|     3.0|      5.0|\n|31   |     3.0|     1.0|     3.5|      4.0|\n|32   |     2.5|     3.0|     7.0|     14.5|\n|33   |     2.0|     1.0|     4.5|      5.5|\n|34   |     1.0|     2.0|     2.5|      3.0|\n|35   |     1.0|     2.5|     1.5|      2.0|\n|36   |     3.0|     6.0|    11.5|     24.0|\n|37   |     0.5|     1.0|     0.5|        0|\n|38   |     1.0|     3.0|     3.5|      3.5|\n|39   |     2.5|     1.5|     2.5|      4.0|\n|40   |     3.5|     3.0|     4.0|      9.0|\n\n\n:::\n:::\n\n::: {#tbl-itemrestscore40 .cell tbl-cap='Item-restscore detection rate with 40 items (3 misfit)'}\n\n```{.r .cell-code .hidden}\nir40_df %>% \n  group_by(samplesize) %>% \n  filter(ir_padj == \"sign. misfit\") %>% \n  count(item, .drop = F) %>% \n  mutate(Percent = n*100/500) %>% \n  ungroup() %>% \n    mutate(samplesize = factor(samplesize, levels = c(150,250,500,1000,2000),\n                             labels = c(\"n = 150\",\n                                        \"n = 250\",\n                                        \"n = 500\",\n                                        \"n = 1000\",\n                                        \"n = 2000\"))) %>% \n  rename(`Sample size` = samplesize,\n         Item = item,\n         `Percent misfit` = Percent) %>% \n  select(!n) %>% \n  pivot_wider(id_cols = c(Item), names_from = c(`Sample size`),\n              values_from = `Percent misfit`) %>% \n  mutate(Item = factor(Item, levels = 1:40, ordered = T)) %>% \n  arrange(Item) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Item | n = 150| n = 250| n = 500| n = 1000|\n|:----|-------:|-------:|-------:|--------:|\n|1    |     3.4|     3.2|     2.6|      4.4|\n|2    |     2.0|     1.2|     0.8|      2.4|\n|3    |     1.0|     1.0|     1.0|      0.4|\n|4    |     3.0|     1.8|     2.0|      5.6|\n|5    |     1.4|     1.6|     1.6|      0.8|\n|6    |     0.8|     0.2|     0.4|      0.2|\n|7    |     1.6|     1.2|     3.2|      7.4|\n|8    |     3.2|     1.8|     2.2|      3.8|\n|9    |    67.6|    95.2|   100.0|    100.0|\n|10   |     1.6|     2.0|     1.6|      4.0|\n|11   |     0.8|     1.6|     1.6|      1.8|\n|12   |     3.2|     1.4|     0.6|      1.2|\n|13   |    25.2|    56.0|    92.8|    100.0|\n|14   |       0|     0.4|     1.0|        0|\n|15   |     2.0|     1.8|     3.2|      5.4|\n|16   |     2.8|     1.6|     1.8|      1.2|\n|17   |     2.2|     1.6|     1.4|      1.2|\n|18   |    53.6|    88.0|    99.8|    100.0|\n|19   |     1.0|     0.4|     1.0|      1.8|\n|20   |     0.6|     1.0|     0.8|        0|\n|21   |     2.4|     3.6|     4.0|      7.0|\n|22   |     1.0|     0.4|     0.2|      0.6|\n|23   |     1.6|     1.4|     2.4|      2.8|\n|24   |     3.4|     0.8|     0.6|      0.8|\n|25   |     0.4|     0.8|     0.6|      1.6|\n|26   |     1.4|     1.6|     0.8|      1.8|\n|27   |     0.8|     0.6|     1.8|      2.2|\n|28   |     0.6|     0.6|     0.2|      1.6|\n|29   |     1.6|     2.0|     2.6|      5.8|\n|30   |     1.6|     1.0|     1.0|      0.8|\n|31   |     0.6|     2.0|     2.2|      2.8|\n|32   |     1.8|     2.6|     3.4|      7.0|\n|33   |     2.0|     1.6|     0.8|      2.2|\n|34   |     1.2|     1.6|     1.6|      1.6|\n|35   |     1.0|     0.6|     1.2|      1.6|\n|36   |     2.4|     3.8|     8.6|     19.2|\n|37   |     0.8|     0.6|     0.6|      0.8|\n|38   |     1.6|     1.0|     0.6|      1.2|\n|39   |     3.0|     1.6|     1.6|      2.0|\n|40   |     1.4|     2.0|     2.8|      6.0|\n\n\n:::\n:::\n\n\n\n\n\n\n## Session info\n\nThis documents the specific R packages and versions used in this study. Note that the simulations were conducted using `easyRasch` version 0.3.3, while the plots and tables generated directly from `easyRasch` were done using version 0.3.3.2.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.4.3 (2025-02-28)\nPlatform: aarch64-apple-darwin20\nRunning under: macOS Sequoia 15.3.1\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0\n\nlocale:\n[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8\n\ntime zone: Europe/Stockholm\ntzcode source: internal\n\nattached base packages:\n [1] parallel  grid      stats4    stats     graphics  grDevices utils    \n [8] datasets  methods   base     \n\nother attached packages:\n [1] showtext_0.9-7    showtextdb_3.0    sysfonts_0.8.9    arrow_16.1.0     \n [5] easyRasch_0.3.5   doParallel_1.0.17 iterators_1.0.14  furrr_0.3.1      \n [9] future_1.34.0     foreach_1.5.2     janitor_2.2.0     hexbin_1.28.4    \n[13] catR_3.17         glue_1.8.0        ggrepel_0.9.6     patchwork_1.3.0  \n[17] reshape_0.8.9     matrixStats_1.4.1 psychotree_0.16-1 psychotools_0.7-4\n[21] partykit_1.2-22   mvtnorm_1.3-1     libcoin_1.0-10    psych_2.4.6.26   \n[25] mirt_1.43         lattice_0.22-6    kableExtra_1.4.0  formattable_0.2.1\n[29] lubridate_1.9.3   forcats_1.0.0     stringr_1.5.1     dplyr_1.1.4      \n[33] purrr_1.0.2       readr_2.1.5       tidyr_1.3.1       tibble_3.2.1     \n[37] tidyverse_2.0.0   ggdist_3.3.2      iarm_0.4.3        ggplot2_3.5.1    \n[41] eRm_1.0-6        \n\nloaded via a namespace (and not attached):\n  [1] splines_4.4.3        R.oo_1.26.0          cellranger_1.1.0    \n  [4] rpart_4.1.24         lifecycle_1.0.4      rprojroot_2.0.4     \n  [7] globals_0.16.3       vroom_1.6.5          MASS_7.3-64         \n [10] backports_1.5.0      magrittr_2.0.3       vcd_1.4-12          \n [13] Hmisc_5.2-2          rmarkdown_2.28       yaml_2.3.10         \n [16] sessioninfo_1.2.2    pbapply_1.7-2        RColorBrewer_1.1-3  \n [19] abind_1.4-5          audio_0.1-11         quadprog_1.5-8      \n [22] R.utils_2.12.3       nnet_7.3-20          listenv_0.9.1       \n [25] testthat_3.2.1.1     RPushbullet_0.3.4    vegan_2.6-8         \n [28] parallelly_1.38.0    svglite_2.1.3        permute_0.9-7       \n [31] codetools_0.2-20     xml2_1.3.6           tidyselect_1.2.1    \n [34] farver_2.1.2         base64enc_0.1-3      jsonlite_1.8.9      \n [37] progressr_0.14.0     Formula_1.2-5        survival_3.8-3      \n [40] systemfonts_1.1.0    tools_4.4.3          gnm_1.1-5           \n [43] snow_0.4-4           Rcpp_1.0.14          mnormt_2.1.1        \n [46] gridExtra_2.3        xfun_0.46            here_1.0.1          \n [49] mgcv_1.9-1           distributional_0.4.0 ca_0.71.1           \n [52] withr_3.0.2          beepr_2.0            fastmap_1.2.0       \n [55] digest_0.6.37        timechange_0.3.0     R6_2.5.1            \n [58] colorspace_2.1-1     R.methodsS3_1.8.2    inum_1.0-5          \n [61] generics_0.1.3       data.table_1.16.0    SimDesign_2.17.1    \n [64] htmlwidgets_1.6.4    pkgconfig_2.0.3      gtable_0.3.5        \n [67] lmtest_0.9-40        brio_1.1.5           htmltools_0.5.8.1   \n [70] carData_3.0-5        scales_1.3.0         snakecase_0.11.1    \n [73] knitr_1.48           rstudioapi_0.17.1    tzdb_0.4.0          \n [76] checkmate_2.3.2      nlme_3.1-167         curl_6.1.0          \n [79] zoo_1.8-12           relimp_1.0-5         vcdExtra_0.8-5      \n [82] foreign_0.8-88       pillar_1.10.1        vctrs_0.6.5         \n [85] car_3.1-2            Deriv_4.1.3          cluster_2.1.8       \n [88] dcurver_0.9.2        archive_1.1.8        GPArotation_2024.3-1\n [91] htmlTable_2.4.3      evaluate_1.0.1       cli_3.6.3           \n [94] compiler_4.4.3       rlang_1.1.4          crayon_1.5.3        \n [97] future.apply_1.11.2  labeling_0.4.3       plyr_1.8.9          \n[100] stringi_1.8.4        viridisLite_0.4.2    assertthat_0.2.1    \n[103] munsell_0.5.1        Matrix_1.7-2         qvcalc_1.0.3        \n[106] hms_1.1.3            bit64_4.0.5          bit_4.0.5           \n[109] readxl_1.4.3        \n```\n\n\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{longtable}\n\\usepackage{array}\n\\usepackage{multirow}\n\\usepackage{wrapfig}\n\\usepackage{float}\n\\usepackage{colortbl}\n\\usepackage{pdflscape}\n\\usepackage{tabu}\n\\usepackage{threeparttable}\n\\usepackage{threeparttablex}\n\\usepackage[normalem]{ulem}\n\\usepackage{makecell}\n\\usepackage{xcolor}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}