project:
  type: manuscript

repo-url: https://github.com/pgmj/rasch_itemfit
#osf-url:
#preprint-url:

execute:
  freeze: auto
  warning: false
  message: false

format:
  html:
    toc: true

  pdf:
    number-sections: false
    notebook-links: global

  apaquarto-docx:
    fig-dpi: 175
    number-sections: false


