project:
  type: manuscript

execute:
  freeze: auto
  warning: false
  message: false

format:
  html:
    toc: true
    number-sections: true
    citations-hover: true
    crossrefs-hover: true
    other-links:
      - text: Journal website (with PDF)
        icon: file-pdf
        href: https://www.emp-open.de/abstract?article_id=145
      - text: GitHub code repository
        icon: file-code
        href: https://github.com/pgmj/rasch_itemfit
      - text: OSF preprint
        icon: file-pdf
        href: https://osf.io/preprints/osf/j8fg2
    comments:
      hypothesis: true
    csl: apa.csl

  # pdf:
  #   number-sections: false
  #   notebook-links: global
  #   csl: apa.csl

  # apaquarto-docx:
  #   fig-dpi: 175
  #   number-sections: false
  #   csl: apa.csl
  
  # preprint-typst:
  #   number-sections: true
  #   running-head: "*Preprint:* Detecting item misfit in Rasch models"
  #   authornote: This manuscript is currently under peer-review.
  #   citeproc: true
  #   csl: https://www.zotero.org/styles/apa-with-abstract

