project:
  type: manuscript

execute:
  freeze: auto
  warning: false
  message: false

format:
  html:
    toc: true
    citations-hover: true
    crossrefs-hover: true
    other-links:
      - text: GitHub repo
        icon: file-code
        href: https://github.com/pgmj/rasch_itemfit
  #    - text: OSF Preprint
        
    comments:
      hypothesis: true
      
  pdf:
    number-sections: false
    notebook-links: global

  apaquarto-docx:
    fig-dpi: 175
    number-sections: false


