project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
  pdf:
    number-sections: false
    reference-doc: custom-reference-doc.docx
  apaquarto-docx:
    fig-dpi: 175
    number-sections: false

